### ISSUE TITLE
Consecutive semantic reference head->head->...->head

### ISSUE THREAD

**Issue by windrg** [Valloric/ycmd#390] opened 2016-02-24 13:53 UTC
Hi Valloric,

When I'm trying to find a consecutive series of a member of a structure, e.g head in a list.
It shows at the first time. but it doesn't work any more from the 2nd time.
head->head : works
head->head-> : this shows the below error.
```


2-24 22:34:02,292 - ERROR - Exception from semantic completer (using general): Traceback (most recent call last):
  File "/home/cysh/.emacs.d/bin/ycmd/ycmd/../ycmd/handlers.py", line 111, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/home/cysh/.emacs.d/bin/ycmd/ycmd/../ycmd/completers/completer.py", line 168, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/home/cysh/.emacs.d/bin/ycmd/ycmd/../ycmd/completers/completer.py", line 184, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/home/cysh/.emacs.d/bin/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 112, in ComputeCandidatesInner
    raise RuntimeError( NO_COMPLETIONS_MESSAGE )
RuntimeError: No completions found; errors in the file?

2016-02-24 22:34:02,492 - INFO - Received completion request
2016-02-24 22:34:02,493 - DEBUG - Using filetype completion: True
2016-02-24 22:34:02,500 - ERROR - Exception from semantic completer (using general): Traceback (most recent call last):
  File "/home/cysh/.emacs.d/bin/ycmd/ycmd/../ycmd/handlers.py", line 111, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/home/cysh/.emacs.d/bin/ycmd/ycmd/../ycmd/completers/completer.py", line 168, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/home/cysh/.emacs.d/bin/ycmd/ycmd/../ycmd/completers/completer.py", line 184, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/home/cysh/.emacs.d/bin/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 112, in ComputeCandidatesInner
    raise RuntimeError( NO_COMPLETIONS_MESSAGE )
RuntimeError: No completions found; errors in the file?
```

**Comment by micbou** [comment] 2016-02-24 16:11
I cannot reproduce your issue (in Vim):

![ycmd-issue-390](https://cloud.githubusercontent.com/assets/10026824/13291283/7500dcb0-db17-11e5-821e-7f190f0de352.gif)
You have probably an error in your code. Could you provide a minimal test case?

**Comment by Valloric** [comment] 2016-02-24 18:51
This is extremely highly unlikely to be a bug in ycmd since there's nothing specific about following chains of pointers that ycmd would handle differently than any other completion. If there is a bug, it's in libclang, not ycmd. It's more likely that you had an error in your code since @micbou can't repro this. Closing.

**Closed by Valloric** 2016-02-24 18:51 UTC
