### ISSUE TITLE
Clang error parsing headers?

### ISSUE THREAD

**Issue by joelfrederico** [Valloric/ycmd#937] opened 2018-02-23 23:00 UTC
Hello, All. I have an issue I've been able to distill to a simple test case. I've been able to test on two platforms, Mac and Windows. Mac doesn't have an issue, but Windows does.

Of course, the setup is everything, so here goes.

First, things you'll need:

- Windows environment (of course)
- YouCompleteMe (all set up, etc.)

Next, here's the code:

[cmake_test.zip](https://github.com/Valloric/ycmd/files/1753390/cmake_test.zip)

Extract it to C:\cmake_test. Then open Vim. Using Vim, open C:\cmake_test\main.cpp. Then open C:\cmake_test\head.h. You'll notice I made a silly coding error: I forget the "c" on the definition of the class Classy:

`head.h, line 6: lass Classy {`

That's wrong. On Mac, if you were to generate the compile_commands.json via CMake, ycmd detects my error:

`unknown type name 'lass'; did you mean 'class'? (Fixit)`

On Windows, I get a red error:

`ClangParseError: An AST deserialization error occurred while parsing the translation unit.`

If you like, I can give instructions on how I generate the compile_commands.json. That should be unnecessary, though. I'm not sure if this is a ycmd issue or a Clang issue.

Of course, if I fix my error and compile, the program works (and of course appears to do nothing) on both platforms.

Any ideas? Is this related to #892?

**Comment by joelfrederico** [comment] 2018-02-23 23:08
Also, if I rename head.h to head.hpp and clang-check, I get the correct error.

`> clang-check head.hpp -p C:\`

That's with clang 5.0.1.

**Comment by bstaletic** [comment] 2018-02-23 23:10
Which version of LLVM and Visual Studio are you using?

**Comment by joelfrederico** [comment] 2018-02-23 23:11
LLVM is 5.0.1. Visual Studio is 2015. CMake is 3.10 (used to generate compile_commands.json).

**Comment by joelfrederico** [comment] 2018-02-23 23:20
Hmmm I should clarify- and add the Vim version.

- Vim: 8.0.1399 64-bit
- YouCompleteMe/ycmd: Compiled against LLVM 5.0.1 64-bit, Python 3.6.3 64-bit
- LLVM at the command-line: 5.0.1 32-bit
- Visual Studio 2015

Used to generate compile_commands:

- CMake 3.10.0
- Ninja 1.8.2

**Comment by micbou** [comment] 2018-02-24 04:26
Thanks for providing a test case. The AST deserialization error is due to the `C:\\cmake_test\\main.cpp` path at the end of the flags. Libclang doesn't like stray file paths. We have code to handle them but not for Windows paths. This should be fixed by PR https://github.com/Valloric/ycmd/pull/938.

**Closed** 2018-02-24 17:40 UTC

**Comment by micbou** [comment] 2018-02-24 20:16
@joelfrederico Can you confirm the issue is fixed by PR #938? You may still notice an AST error but it should only happen the first time the file is parsed.

**Comment by joelfrederico** [comment] 2018-02-24 20:33
It seems to fix this specific issue, but I'm getting an error message about crashes in a slightly different scenario. I'll need to prepare another example, which I probably won't have time to do until Monday.

**Comment by joelfrederico** [comment] 2018-02-24 20:46
Thanks so much @micbou by the way, this will make coding much easier for me!
