### ISSUE TITLE
[Feature] Language server protocol support

### ISSUE THREAD

**Issue by rski** [Valloric/ycmd#663] opened 2016-12-04 15:05 UTC
Microsoft has published a spec for a thing called language server protocol:

https://github.com/Microsoft/language-server-protocol
> The Language Server protocol is used between a tool (the client) and a language smartness provider (the server) to integrate features like auto complete, goto definition, find all references and alike into the tool.

It might be a good idea to implement support for this protocol and integrate backends talking this protocol in ycmd. Then editors get LSP support for free, using their standard ycmd plugins. Basically what I have in mind is using the existing ycmd codebase as a lightweight wrapper around LSP.

Pros:
- Vim/Emacs/Atom/etc get support for LSP backends without having to implement clients for this, they can just use their ycmd plugins
- ycmd can add support for a lot of languages using LSP, like java (I think it would be pretty cool to have good java autocompletion in vim/emacs without eclim):
https://github.com/Microsoft/language-server-protocol/wiki/Protocol-Implementations
- It might be possible to reduce some complexity inside ycmd and move it to LSP instead of doing a custom thing.

Caveats: 
- I know ycmd has security concerns,  I have no idea how LSP/json-rpc addresses that.
- I haven't evaluated json-rpc clients ycmd could integrate with.

**Comment by vheon** [comment] 2016-12-04 19:01
I believe this is a duplicate of #515.

**Closed by vheon** 2016-12-04 19:01 UTC

**Comment by rski** [comment] 2016-12-04 19:04
whoop, sorry I only looked at the open tickets for potential duplicates
