### ISSUE TITLE
ycmd server wont start because it can't load clang.so.4 - which exists

### ISSUE THREAD

**Issue by xinquanatcolezhu** [Valloric/ycmd#807] opened 2017-08-02 08:08 UTC
As my current CentoOS's libstdc++.so version does not have GLIBCXX_3.4.20, which is required by the downloaded libclang from the build script . I have to build ycmd using my system libclang

`./build.py --clang-completer --system-libclang`

The building process was successful but when i try to run ycmd with below command it gives me error could not find the libclang.  but the clang.so exists in my ycmd directory.

Please help!

# Issue Details
**[xinquan.zhu@jpdla00071 ycmd]$ python ycmd/ --options_file ycmd/default_settings.json** 
2017-08-02 09:38:29,231 - ERROR - libclang.so.4: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/AD/xinquan.zhu/s/ycmd/ycmd/server_utils.py", line 96, in CompatibleWithCurrentCore
    ycm_core = ImportCore()
  File "/home/AD/xinquan.zhu/s/ycmd/ycmd/server_utils.py", line 88, in ImportCore
    import ycm_core as ycm_core
ImportError: libclang.so.4: cannot open shared object file: No such file or directory

[xinquan.zhu@jpdla00071 ycmd]$ ls -lrt
total 1139940
-rw-r--r--  1 xinquan.zhu domain users       4938 Aug  2 08:43 DEV_SETUP.md
-rw-r--r--  1 xinquan.zhu domain users          3 Aug  2 08:43 CORE_VERSION
-rw-r--r--  1 xinquan.zhu domain users      35147 Aug  2 08:43 COPYING.txt
-rw-r--r--  1 xinquan.zhu domain users       8320 Aug  2 08:43 CONTRIBUTING.md
-rw-r--r--  1 xinquan.zhu domain users       2385 Aug  2 08:43 CODE_OF_CONDUCT.md
-rw-r--r--  1 xinquan.zhu domain users        880 Aug  2 08:43 Vagrantfile
-rw-r--r--  1 xinquan.zhu domain users       4748 Aug  2 08:43 TESTS.md
-rw-r--r--  1 xinquan.zhu domain users      14612 Aug  2 08:43 README.md
-rwxr-xr-x  1 xinquan.zhu domain users       1226 Aug  2 08:43 benchmark.py
-rw-r--r--  1 xinquan.zhu domain users       1231 Aug  2 08:43 appveyor.yml
drwxr-xr-x  3 xinquan.zhu domain users       4096 Aug  2 08:43 clang_includes
drwxr-xr-x  4 xinquan.zhu domain users       4096 Aug  2 08:43 ci
-rwxr-xr-x  1 xinquan.zhu domain users      19377 Aug  2 08:43 build.py
-rw-r--r--  1 xinquan.zhu domain users        773 Aug  2 08:43 codecov.yml
drwxr-xr-x  5 xinquan.zhu domain users       4096 Aug  2 08:43 cpp
-rwxr-xr-x  1 xinquan.zhu domain users       5689 Aug  2 08:43 update_boost.py
-rw-r--r--  1 xinquan.zhu domain users        188 Aug  2 08:43 tox.ini
drwxr-xr-x 14 xinquan.zhu domain users       4096 Aug  2 08:43 third_party
-rw-r--r--  1 xinquan.zhu domain users        805 Aug  2 08:43 test_requirements.txt
-rwxr-xr-x  1 xinquan.zhu domain users        509 Aug  2 08:43 style_format.sh
-rwxr-xr-x  1 xinquan.zhu domain users       7632 Aug  2 08:43 run_tests.py
drwxr-xr-x  3 xinquan.zhu domain users       4096 Aug  2 08:43 examples
-rw-r--r--  1 xinquan.zhu domain users       4771 Aug  2 08:43 vagrant_bootstrap.sh
drwxr-xr-x  2 xinquan.zhu domain users       4096 Aug  2 08:45 clang_archives
-rwxr-xr-x  1 xinquan.zhu domain users    2697024 Aug  2 09:29 ycm_core.so
**-rwxr-xr-x  1 xinquan.zhu domain users 1164395632 Aug  2 09:29 libclang.so.4.0**
**lrwxrwxrwx  1 xinquan.zhu domain users         15 Aug  2 09:29 libclang.so.4 -> libclang.so.4.0**
-rw-r--r--  1 xinquan.zhu domain users         15 Aug  2 09:29 PYTHON_USED_DURING_BUILDING
drwxr-xr-x  4 xinquan.zhu domain users       4096 Aug  2 09:38 ycmd

**Comment by micbou** [comment] 2017-08-02 11:06
What's the output of the following commands:
```sh
ldd /home/AD/xinquan.zhu/s/ycmd/ycm_core.so
objdump -x /home/AD/xinquan.zhu/s/ycmd/ycm_core.so | grep RPATH
ldconfig -p | grep libclang
```
?

**Comment by xinquanatcolezhu** [comment] 2017-08-02 23:33
thanks so much for the hints!! somehow my libclang.so is not in the ldconfig cache!!!  how did that happen? 

[xinquan.zhu@jpdla00071 ~]$ objdump -x  /home/AD/xinquan.zhu/s/ycmd/ycm_core.so | grep RPATH
  RPATH                /usr/lib64/python2.7/config

[xinquan.zhu@jpdla00071 ~]$ ldd /home/AD/xinquan.zhu/s/ycmd/ycm_core.so
	linux-vdso.so.1 =>  (0x00007ffeb57ae000)
	libpython2.7.so.1.0 => /lib64/libpython2.7.so.1.0 (0x00007fe876e0d000)
	**libclang.so.4 => not found**
	librt.so.1 => /lib64/librt.so.1 (0x00007fe876c04000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fe8768fb000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fe8765f8000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fe8763e2000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fe876021000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe875e04000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fe875c00000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007fe8759fd000)
	/lib64/ld-linux-x86-64.so.2 (0x0000556c68c8c000)

**Comment by xinquanatcolezhu** [comment] 2017-08-03 03:54
and my system libclang is at 

```
./local/lib/libclang.so
./local/lib/libclangIndex.a
./local/lib/libclang.so.4.0

```

**Comment by micbou** [comment] 2017-08-03 11:30
Could you try adding the directory containing `libclang.so` to the `LD_LIBRARY_PATH` environment variable?

**Comment by xinquanatcolezhu** [comment] 2017-08-03 13:41
thanks so much!!! . i solved the problem by adding it. but now it gives another error 
I just copied the extra_conf.py from github somewhere, when I open a c++ file in emacs
This c++ file is under a project which has cmake compile_commands.json files (my cmakefile has external projects)

I got confused where can i specify the compile_commands path to ycmd so that it reads it and parse my source code???

src/test.cpp
build/compile_commands.json

2017-08-03 22:31:42,250 - DEBUG - Global extra conf not loaded or no function YcmCorePreload                                                                                                  
serving on http://127.0.0.1:44719   

this my settings in emacs
```
;;ycmd                                                                                                                                                                                        
(require 'ycmd)                                                                                                                                                                               
(add-hook 'c-mode-common-hook 'ycmd-mode)                                                                                                                                                     
(require 'flycheck-ycmd)                                                                                                                                                                      
(flycheck-ycmd-setup)                                                                                                                                                                         
(require 'company-ycmd)                                                                                                                                                                       
(company-ycmd-setup)                                                                                                                                                                          
(setq ycmd-server-command '("python" "/home/AD/xinquan.zhu/s/ycmd/ycmd/"))                                                                                                                                                                                                                                 
(set-variable 'ycmd-global-config "/home/AD/xinquan.zhu/Dropbox/ycm_extra_conf.py")         

```

This is my  ycm_extra_conf.py

import os
import ycm_core

# These are the compilation flags that will be used in case there's no
# compilation database set (by default, one is not set).
# CHANGE THIS LIST OF FLAGS. YES, THIS IS THE DROID YOU HAVE BEEN LOOKING FOR.
flags = [
'-Wall',
'-Wextra',
'-Werror',
'-Wno-long-long',
'-Wno-variadic-macros',
'-fexceptions',
'-DNDEBUG',
# You 100% do NOT need -DUSE_CLANG_COMPLETER in your flags; only the YCM
# source code needs it.
'-DUSE_CLANG_COMPLETER',
# THIS IS IMPORTANT! Without a "-std=<something>" flag, clang won't know which
# language to use when compiling headers. So it will guess. Badly. So C++
# headers will be compiled as C headers. You don't want that so ALWAYS specify
# a "-std=<something>".
# For a C project, you would set this to something like 'c99' instead of
# 'c++11'.
'-std=c++11',
# ...and the same thing goes for the magic -x option which specifies the
# language that the files to be compiled are written in. This is mostly
# relevant for c++ headers.
# For a C project, you would set this to 'c' instead of 'c++'.
'-x',
'c++',
'-isystem',
'../BoostParts',
'-isystem',
# This path will only work on OS X, but extra paths that don't exist are not
# harmful
'/System/Library/Frameworks/Python.framework/Headers',
'-isystem',
'../llvm/include',
'-isystem',
'../llvm/tools/clang/include',
'-I',
'.',
'-I',
'./ClangCompleter',
'-isystem',
'./tests/gmock/gtest',
'-isystem',
'./tests/gmock/gtest/include',
'-isystem',
'./tests/gmock',
'-isystem',
'./tests/gmock/include',
]


# Set this to the absolute path to the folder (NOT the file!) containing the
# compile_commands.json file to use that instead of 'flags'. See here for
# more details: http://clang.llvm.org/docs/JSONCompilationDatabase.html
#
# You can get CMake to generate this file for you by adding:
#   set( CMAKE_EXPORT_COMPILE_COMMANDS 1 )
# to your CMakeLists.txt file.
#
# Most projects will NOT need to set this to anything; you can just change the
# 'flags' list of compilation flags. Notice that YCM itself uses that approach.
compilation_database_folder = ''

if os.path.exists( compilation_database_folder ):
  database = ycm_core.CompilationDatabase( compilation_database_folder )
else:
  database = None

SOURCE_EXTENSIONS = [ '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]

def DirectoryOfThisScript():
  return os.path.dirname( os.path.abspath( __file__ ) )


def MakeRelativePathsInFlagsAbsolute( flags, working_directory ):
  if not working_directory:
    return list( flags )
  new_flags = []
  make_next_absolute = False
  path_flags = [ '-isystem', '-I', '-iquote', '--sysroot=' ]
  for flag in flags:
    new_flag = flag

    if make_next_absolute:
      make_next_absolute = False
      if not flag.startswith( '/' ):
        new_flag = os.path.join( working_directory, flag )

    for path_flag in path_flags:
      if flag == path_flag:
        make_next_absolute = True
        break

      if flag.startswith( path_flag ):
        path = flag[ len( path_flag ): ]
        new_flag = path_flag + os.path.join( working_directory, path )
        break

    if new_flag:
      new_flags.append( new_flag )
  return new_flags


def IsHeaderFile( filename ):
  extension = os.path.splitext( filename )[ 1 ]
  return extension in [ '.h', '.hxx', '.hpp', '.hh' ]


def GetCompilationInfoForFile( filename ):
  # The compilation_commands.json file generated by CMake does not have entries
  # for header files. So we do our best by asking the db for flags for a
  # corresponding source file, if any. If one exists, the flags for that file
  # should be good enough.
  if IsHeaderFile( filename ):
    basename = os.path.splitext( filename )[ 0 ]
    for extension in SOURCE_EXTENSIONS:
      replacement_file = basename + extension
      if os.path.exists( replacement_file ):
        compilation_info = database.GetCompilationInfoForFile(
          replacement_file )
        if compilation_info.compiler_flags_:
          return compilation_info
    return None
  return database.GetCompilationInfoForFile( filename )


def FlagsForFile( filename, **kwargs ):
  if database:
    # Bear in mind that compilation_info.compiler_flags_ does NOT return a
    # python list, but a "list-like" StringVec object
    compilation_info = GetCompilationInfoForFile( filename )
    if not compilation_info:
      return None

    final_flags = MakeRelativePathsInFlagsAbsolute(
      compilation_info.compiler_flags_,
      compilation_info.compiler_working_dir_ )

    # NOTE: This is just for YouCompleteMe; it's highly likely that your project
    # does NOT need to remove the stdlib flag. DO NOT USE THIS IN YOUR
    # ycm_extra_conf IF YOU'RE NOT 100% SURE YOU NEED IT.
    try:
      final_flags.remove( '-stdlib=libc++' )
    except ValueError:
      pass
  else:
    relative_to = DirectoryOfThisScript()
    final_flags = MakeRelativePathsInFlagsAbsolute( flags, relative_to )

  return { 'flags': final_flags }

**Comment by micbou** [comment] 2017-08-03 21:32
This is explained in [this section of the docs](https://github.com/Valloric/YouCompleteMe#option-1-use-a-compilation-database):
> YCM looks for a file named compile_commands.json in the directory of the opened file or in any directory above it in the hierarchy (recursively); when the file is found, it is loaded.

Given that, you could create a symlink of the `build/compile_commands.json` file at the root of your project. Another solution is to copy your `.ycm_extra_conf.py` file to the project root and set the variable `compilation_database_folder` to the absolute path of the `build` directory.

**Comment by xinquanatcolezhu** [comment] 2017-08-09 13:01
thanks . I followed your suggestions 

`compilation_database_folder = '/home/AD/xinquan.zhu/oms/build/'`

where the build folder has compile_commands.json file 

then set my global-config file 

`(set-variable 'ycmd-global-config "/home/AD/xinquan.zhu/oms/ycm_extra_conf.py")`

when  i open the srouce code under my oms/ it does not work. it gives me below error in my emacs mini-buffer

> REQUEST [error] Error (error) while connecting to http://127.0.0.1:33557/event_notification. 

when i open the ycmd server log it shows 

> 2017-08-09 21:53:53,353 - DEBUG - Global extra conf not loaded or no function YcmCorePreload                                                                                                  
> serving on http://127.0.0.1:33557  


Could you kindly help me out. I am quite stress out as I spent lots of time try to make it work. i do believe ycmd should be a good unix c++ development tool

**Comment by micbou** [comment] 2017-08-09 17:08
Could you paste the output of the command `ycmd-show-debug-info` while editing one of your C++ files?

**Comment by xinquanatcolezhu** [comment] 2017-08-09 23:36
its quite strange, for example, if I run a random type ycmd-get-type 

the mini-buffer shows

> REQUEST [error] Error (error) while connecting to http://127.0.0.1:38507/run_completer_command. 


however the *ycmd-debug-info* does not give much information

> Ycmd debug information for buffer OMS.cpp in c++-mode:                                                                                                                                        
>                                                                                                                                                                                               
> No debug info available from server                                                                                                                                                           
>                                                                                                                                                                                               
> Server is running at: 127.0.0.1:38507                                                                                                                                                         
>                                                                       
> 
>                                                                                                                         
> Ycmd Mode is enabled                                                                                                                                                                          
>                                                                                                                                                                                               
> --------------------                                                                                                                                                                          
>                                                                                                                                                                                               
> Ycmd version:   1.2                                                                                                                                                                           
> Emacs version:  25.2.1                                                                                                                                                                        
> System:         x86_64-unknown-linux-gnu                                                                                                                                                      
> Window system:  nil                                                                                                                                                                           
>

**Comment by micbou** [comment] 2017-08-10 20:08
So, the ycmd server is running but the emacs client is unable to connect to it. Run the following command in a terminal:
```
curl -X get 127.0.0.1:{port}/ready
```
where `{port}` is the port displayed in `ycmd-debug-info`. This command should return:
```json
{"exception": null, "traceback": null, "message": "None"}
```
Then check that the ycmd logfile shows the message:
```
INFO - Dropping request with bad HMAC
```
If that's the case then it's a problem with the emacs client and you should [open an issue there](https://github.com/abingham/emacs-ycmd).

**Comment by xinquanatcolezhu** [comment] 2017-08-11 02:19
thanks!!! I figured out that my company have this proxy blocking all the http reqeust 
After I set the environment 

export no_proxy="localhost,127.0.0.1"
the  `{"exception": null, "traceback": null, "message": "None"}` comes back.

however, I have got libclang crashed in my ycmd-server buffer  :-(

```
2017-08-11 11:10:41,527 - INFO - Adding buffer identifiers for file: /home/AD/xinquan.zhu/oms/src/OMSNode.cpp
python: /home/AD/xinquan.zhu/Downloads/cfe-4.0.0.src/include/clang/Basic/SourceLocation.h:319: bool clang::FullSourceLoc::isBeforeInTranslationUnitThan(clang::FullSourceLoc) const: Assertion `SrcMgr == Loc.SrcMgr && "Loc comes from another SourceManager!"' failed.
libclang: crash detected during parsing: {
```

:(

**Comment by micbou** [comment] 2017-08-12 11:21
> thanks!!! I figured out that my company has this proxy blocking the http reqeust
> After I set the environment
> export no_proxy="localhost,127.0.0.1"
> the{"exception": null, "traceback": null, "message": "None"}
> comes back!!!!!!!!!!!!!!!1

Recent versions of emacs-ycmd take care of that. See PR https://github.com/abingham/emacs-ycmd/pull/438.

> however, I have got the ycmd coredumped with libclang crashed in my ycmd-server buffer :-(

Could you open a new issue with a minimal testcase (C++ file and compilation flags) that reproduces the crash? I am closing this one since the initial issue is resolved.

**Closed by micbou** 2017-08-12 11:21 UTC
