### ISSUE TITLE
The python process locks my c++ header file.

### ISSUE THREAD

**Issue by lorry-lee** [Valloric/ycmd#858] opened 2017-10-16 13:24 UTC
I don't have a specific reproduce step, when I try to delete one of my header file, I found it's locked by Python dll from ycmd. Is that normal?
I'm on windows 10, vim 8, python3.5 32bit, ycmd code version is 31.

**Comment by micbou** [comment] 2017-10-16 19:53
It's most likely caused by libclang. What's the output of `:YcmDebugInfo`?

**Comment by micbou** [comment] 2017-11-02 11:39
No answer. Closing.

**Closed by micbou** 2017-11-02 11:39 UTC
