### ISSUE TITLE
Compiling under windows

### ISSUE THREAD

**Issue by majcl** [Valloric/ycmd#477] opened 2016-05-04 19:21 UTC
I have found a problems with compiling under windows. Specially problems are in gtest-port.h
Using MinGW-W64
This is problem with defined macros: On windows and mingw  
`GTEST_HAS_PTHREAD `and `GTEST_OS_WINDOWS` both are defined. But i suppose in this file  some places assumes these are exclusive - that when `GTEST_OS_WINDOWS` is defined, than `GTEST_HAS_PTHREAD` is not.
Fast fix is to  change line 1458 
`# elif GTEST_HAS_PTHREAD`
to
`# elif GTEST_HAS_PTHREAD && !GTEST_OS_WINDOWS`
(then there one another minor problem with redefinition of `SleepMilliseconds()`, - this can be renamed).
On line 1553 its written, that we dont want to use pthreads on mingw, but line 1458 doesnt take this into account(checks only for `GTEST_HAS_PTHREAD`)

**Comment by vheon** [comment] 2016-05-04 20:49
Please do not delete the Issue Template, just fill it out. That being said MinGW-W64 is not an officially supported platform. We only support compiling ycmd with MSVC. Anyway if that is the only error you have "gtest-port.h" why are you building the tests? Since this is not a bug for a supported platform I'm going to close this.

**Closed by vheon** 2016-05-04 20:49 UTC

**Comment by Valloric** [comment] 2016-05-05 00:31
While we don't support mingw-w64, this compilation issue might be fixed by us updating gtest to the latest version. The version we use is 2+ years old.
