### ISSUE TITLE
It's not working in C++-mode.

### ISSUE THREAD

**Issue by asdyjd** [Valloric/ycmd#771] opened 2017-06-06 13:59 UTC
env: win10 64bit, anaconda3.6.1 64bit. emacs.
When I type something,A dialog pop up.
```
Microsoft Visual C++ Runtime Library
Assertion failed!
Program: D:\emacs\ycmd\libclang.dll
File: D:\src\llvm_package_4.0.0\llvm\tools.../SourceLocation.h Line: 319
Expression: SrcMgr == Loc.SrcMgr && "Loc comes from another SourceManager!"
For information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts
(Press Retry to debug the application - JIT must be enabled)
```
Before this dialog show,`ycmd-debug-show-info` is 
```
Ycmd debug information for buffer main.cpp in c++-mode:


((python (executable . "d:\\Anaconda3\\python.exe") (version . "3.6.1"))
 (clang (has_support . t)
        (version . "clang version 4.0.0 (tags/RELEASE_400/final)"))
 (extra_conf (path . "D:/emacs/ycmd/cpp/ycm/.ycm_extra_conf.py")
             (is_loaded . t))
 (completer (name . "C-family")
            (servers)
            (items ((key . "compilation database path")
                    (value . "None"))
                   ((key . "flags")
                    (value . "['-Wall', '-Wextra', '-Werror', '-Wno-long-long', '-Wno-variadic-macros', '-fexceptions', '-DNDEBUG', '-DUSE_CLANG_COMPLETER', '-std=c++11', '-x', 'c++', '-isystem', 'D:\\\\emacs\\\\ycmd\\\\cpp\\\\ycm\\\\../BoostParts', '-isystem', '/System/Library/Frameworks/Python.framework/Headers', '-isystem', 'D:\\\\emacs\\\\ycmd\\\\cpp\\\\ycm\\\\../llvm/include', '-isystem', 'D:\\\\emacs\\\\ycmd\\\\cpp\\\\ycm\\\\../llvm/tools/clang/include', '-I', 'D:\\\\emacs\\\\ycmd\\\\cpp\\\\ycm\\\\.', '-I', 'D:\\\\emacs\\\\ycmd\\\\cpp\\\\ycm\\\\./ClangCompleter', '-isystem', 'D:\\\\emacs\\\\ycmd\\\\cpp\\\\ycm\\\\./tests/gmock/gtest', '-isystem', 'D:\\\\emacs\\\\ycmd\\\\cpp\\\\ycm\\\\./tests/gmock/gtest/include', '-isystem', 'D:\\\\emacs\\\\ycmd\\\\cpp\\\\ycm\\\\./tests/gmock', '-isystem', 'D:\\\\emacs\\\\ycmd\\\\cpp\\\\ycm\\\\./tests/gmock/include', '-resource-dir=D:\\\\emacs\\\\ycmd\\\\ycmd\\\\..\\\\clang_includes', '-fno-delayed-template-parsing', '-fspell-checking']")))))


Server is running at: 127.0.0.1:5002

Ycmd Mode is enabled

--------------------

Ycmd version:   1.2snapshot (package: 20170515.2255)
Emacs version:  25.2.2
System:         x86_64-w64-mingw32
Window system:  w32
```
`ycmd-server buffer`is
```
2017-06-06 22:01:58,177 - DEBUG - Global extra conf not loaded or no function YcmCorePreload
serving on http://127.0.0.1:5692
2017-06-06 22:01:59,691 - INFO - Received completion request
2017-06-06 22:01:59,694 - DEBUG - Using filetype completion: True
2017-06-06 22:01:59,743 - INFO - Received completion request
2017-06-06 22:01:59,744 - DEBUG - Using filetype completion: True
2017-06-06 22:01:59,745 - ERROR - Exception from semantic completer (using general): Traceback (most recent call last):
  File "D:\emacs\ycmd\ycmd\..\ycmd\handlers.py", line 103, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "D:\emacs\ycmd\ycmd\..\ycmd\completers\completer.py", line 217, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "D:\emacs\ycmd\ycmd\..\ycmd\completers\completer.py", line 233, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "D:\emacs\ycmd\ycmd\..\ycmd\completers\cpp\clang_completer.py", line 95, in ComputeCandidatesInner
    raise RuntimeError( PARSING_FILE_MESSAGE )
RuntimeError: Still parsing file, no completions yet.

2017-06-06 22:01:59,959 - INFO - Received filetype completion available request
2017-06-06 22:02:00,100 - INFO - Received completion request
2017-06-06 22:02:00,101 - DEBUG - Using filetype completion: True
2017-06-06 22:02:00,101 - ERROR - Exception from semantic completer (using general): Traceback (most recent call last):
  File "D:\emacs\ycmd\ycmd\..\ycmd\handlers.py", line 103, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "D:\emacs\ycmd\ycmd\..\ycmd\completers\completer.py", line 217, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "D:\emacs\ycmd\ycmd\..\ycmd\completers\completer.py", line 233, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "D:\emacs\ycmd\ycmd\..\ycmd\completers\cpp\clang_completer.py", line 95, in ComputeCandidatesInner
    raise RuntimeError( PARSING_FILE_MESSAGE )
RuntimeError: Still parsing file, no completions yet.

2017-06-06 22:02:00,222 - INFO - Received command request
```

I compiled ycmd with this:
https://gist.github.com/asdyjd/92f9c4914f68e4bd7bc955df4c969881

It't not working in c++-mode.But it's good in python-mode.

**Comment by vheon** [comment] 2017-06-06 15:31
> It's not working in C++-mode

What does it mean "is not working"? Does the server crash? You do not get the suggestion? You have to force them? You have to be more specific on that and we need a reproducible test case for it.

>  anaconda3.6.1 64bit

I can already tell you that anaconda is not supported, so please try with cPython first.

>  emacs.

It might be a problem of the emacs client so maybe raise an issue over their project where they probably can help you in a faster way being `emacs` their platform as well.

**Comment by puremourning** [comment] 2017-06-06 20:50
If libclang is asserting, report it to the clang devs. It seems a number of people are hitting libclang asserts recently

**Comment by asdyjd** [comment] 2017-06-09 16:04
I tried Python3 32bit and anaconda 32bit.
`ycmd-server`:
```
2017-06-10 00:02:38,574 - ERROR - Error occurred while loading global extra conf D:/emacs/ycmd/cpp/ycm/.ycm_extra_conf.py
Traceback (most recent call last):
  File "D:\emacs\ycmd\ycmd\..\ycmd\extra_conf_store.py", line 94, in _CallGlobalExtraConfMethod
    module = Load( global_ycm_extra_conf, force = True )
  File "D:\emacs\ycmd\ycmd\..\ycmd\extra_conf_store.py", line 173, in Load
    module = LoadPythonSource( _RandomName(), module_file )
  File "D:\emacs\ycmd\ycmd\..\ycmd\utils.py", line 410, in LoadPythonSource
    return importlib.machinery.SourceFileLoader( name, pathname ).load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 251, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "D:/emacs/ycmd/cpp/ycm/.ycm_extra_conf.py", line 32, in <module>
    import ycm_core
ImportError: DLL load failed: %1       Ч   Win32 Ӧ ó     
2017-06-10 00:02:38,577 - ERROR - DLL load failed: %1       Ч   Win32 Ӧ ó     
Traceback (most recent call last):
  File "D:\emacs\ycmd\ycmd\server_utils.py", line 95, in CompatibleWithCurrentCore
    ycm_core = ImportCore()
  File "D:\emacs\ycmd\ycmd\server_utils.py", line 87, in ImportCore
    import ycm_core as ycm_core
ImportError: DLL load failed: %1       Ч   Win32 Ӧ ó     
```
`ycmd-show-debug-info`
```
Ycmd debug information for buffer main.cpp in c++-mode:

No debug info available from server

Server is not running

Ycmd Mode is enabled

--------------------

Ycmd version:   1.2snapshot (package: 20170515.2255)
Emacs version:  25.2.2
System:         x86_64-w64-mingw32
Window system:  w32
```

**Comment by vheon** [comment] 2017-06-13 12:12
> ValueError: No semantic completer exists for filetypes: ['cpp']

This looks like the C-Family completer was not built. Did you pass the `--clang-completer` flag to the `build.py` script?

**Comment by asdyjd** [comment] 2017-06-14 10:09
This time I compiled it successfully with `python build.py --clang-completer`
But when I run emacs with c++-mode,there is a dialog pop up
```
Microsoft Visual C++ Runtime Library
Assertion failed!
Program: D:\emacs\ycmd\libclang.dll
File: D:\src\llvm_package_4.0.0\llvm\tools.../SourceLocation.h Line: 319
Expression: SrcMgr == Loc.SrcMgr && "Loc comes from another SourceManager!"
For information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts
(Press Retry to debug the application - JIT must be enabled)
```
The `ycmd-show-debug-info`is
```
Ycmd debug information for buffer main.cpp in c++-mode:


((python (executable . "d:\\Python36-32\\python.exe") (version . "3.6.1"))
 (clang (has_support . t)
        (version . "clang version 4.0.0 (tags/RELEASE_400/final)"))
 (extra_conf (path . "D:/emacs/ycmd/cpp/ycm/.ycm_extra_conf.py")
             (is_loaded . t))
 (completer (name . "C-family")
            (servers)
            (items ((key . "compilation database path")
                    (value . "None"))
                   ((key . "flags")
                    (value . "['-Wall', '-Wextra', '-Werror', '-Wno-long-long', '-Wno-variadic-macros', '-fexceptions', '-DNDEBUG', '-DUSE_CLANG_COMPLETER', '-std=c++11', '-x', 'c++', '-isystem', 'D:\\\\emacs\\\\ycmd\\\\cpp\\\\ycm\\\\../BoostParts', '-isystem', '/System/Library/Frameworks/Python.framework/Headers', '-isystem', 'D:\\\\emacs\\\\ycmd\\\\cpp\\\\ycm\\\\../llvm/include', '-isystem', 'D:\\\\emacs\\\\ycmd\\\\cpp\\\\ycm\\\\../llvm/tools/clang/include', '-I', 'D:\\\\emacs\\\\ycmd\\\\cpp\\\\ycm\\\\.', '-I', 'D:\\\\emacs\\\\ycmd\\\\cpp\\\\ycm\\\\./ClangCompleter', '-isystem', 'D:\\\\emacs\\\\ycmd\\\\cpp\\\\ycm\\\\./tests/gmock/gtest', '-isystem', 'D:\\\\emacs\\\\ycmd\\\\cpp\\\\ycm\\\\./tests/gmock/gtest/include', '-isystem', 'D:\\\\emacs\\\\ycmd\\\\cpp\\\\ycm\\\\./tests/gmock', '-isystem', 'D:\\\\emacs\\\\ycmd\\\\cpp\\\\ycm\\\\./tests/gmock/include', '-resource-dir=D:\\\\emacs\\\\ycmd\\\\ycmd\\\\..\\\\clang_includes', '-fno-delayed-template-parsing', '-fspell-checking']")))))


Server is running at: 127.0.0.1:13701

Ycmd Mode is enabled

--------------------

Ycmd version:   1.2snapshot (package: 20170515.2255)
Emacs version:  25.2.2
System:         x86_64-w64-mingw32
Window system:  w32
```
`ycmd-server`is
```
2017-06-14 18:03:29,244 - DEBUG - Global extra conf not loaded or no function YcmCorePreload
serving on http://127.0.0.1:13701
2017-06-14 18:03:29,444 - INFO - Received event notification
2017-06-14 18:03:29,444 - DEBUG - Event name: BufferVisit
2017-06-14 18:03:29,584 - INFO - Received event notification
2017-06-14 18:03:29,585 - DEBUG - Event name: FileReadyToParse
2017-06-14 18:03:29,585 - INFO - Adding buffer identifiers for file: d:/project/oj/lintcode/T/T/main.cpp
2017-06-14 18:03:39,631 - INFO - Received debug info request
```

Furthermore,I run `python run_tests.py --clang-completer`
It failed.The result is https://gist.github.com/asdyjd/aac13407aad043b98e7a5c8ab0272c48

**Comment by vheon** [comment] 2017-06-14 11:44
> System:         x86_64-w64-mingw32

Did you compile `ycmd` inside MinGW?

**Comment by asdyjd** [comment] 2017-06-14 12:29
I installed MinGW and Cygwin32,But I put them in the end of env variables.
And just now I renamed the MinGW and Cygwin32 directory to disable them totally.
And re-compiled it. The result is the same as before.

**Comment by zonyitoo** [comment] 2017-08-03 10:45
I have encountered the same problem in my project. My project has a quite huge code base.

Environment:

- YouCompleteMe: latest master commit
- libclang 4.0.1

Relevent logs

```
2017-08-03 18:37:58,542 - ERROR - python: /home/tylerzhong/cfe-4.0.1.src/include/clang/Basic/SourceLocation.h:319: bool clang::FullSourceLoc::isBeforeInTranslationUnitThan(clang::FullSourceLoc) const: Assertion `SrcMgr == Loc.SrcMgr && "Loc comes from another SourceManager!"' failed.
libclang: crash detected during parsing: {
  'source_filename' : '/data1/mm64/tylerzhong/QQMail/mmgamecenter/src/comm/dry/co/local_cache.h'
  'command_line_args' : ['clang', '-Wall', '-Wextra', '-DNDEBUG', '-std=c++11', '-x', 'c++', '-I/usr/local/include/c++/v1', '-I/usr/local/include/c++/4.8.2', '-I/home/tylerzhong/QQMail/comm2/core', '-I/home/tylerzhong/QQMail/comm2/core/log', '-I/home/tylerzhong/QQMail/comm2/core/concurrent', '-I/home/tylerzhong/QQMail/comm2/svrkit', '-I/home/tylerzhong/QQMail/mmcomm/mq/mqsvr', '-I/home/tylerzhong/QQMail/mmcomm/mq/mqsvr/svr', '-I/home/tylerzhong/QQMail/mmcomm/mq/mqsvr/queue', '-I/home/tylerzhong/QQMail/mmcomm/mq/mqsvr/channel', '-I/home/tylerzhong/QQMail/mmcomm/mq/mqworker', '-I/home/tylerzhong/QQMail/mmcomm/mq/mqworker/handler', '-I/home/tylerzhong/QQMail/mmcomm/comm', '-I/home/tylerzhong/QQMail/platform/kv6', '-I/home/tylerzhong/QQMail/platform/kvcomm/comm', '-I/home/tylerzhong/QQMail/3rd/protobuf-2.3.0/src', '-I/home/tylerzhong/QQMail/mm3rd/jsoncpp/include', '-I/home/tylerzhong/QQMail/mm3rd/rapidjson-1.1/include', '-I/home/tylerzhong/QQMail/mm3rd/mysql++/include', '-I/home/tylerzhong/QQMail/mm3rd/gtest/include', '-I/home/tylerzhong/QQMail/mm3rd/curl/include', '-I/home/tylerzhong/QQMail/mmgamecenter/src/svrkit/mmocgamebroker', '-I/home/tylerzhong/QQMail/mmgamecenter/src/svrkit/mmgamefriends', '-I/home/tylerzhong/QQMail/mmgamecenter/src/svrkit/mmgamefeedsdatamq', '-I/home/tylerzhong/QQMail/mmgamecenter/src/svrkit/mmgamefeedslogic', '-I/home/tylerzhong/QQMail/mmgamecenter/src/svrkit/mmgamerecommendation', '-I/home/tylerzhong/QQMail/mmgamecenter/src/svrkit/mmocgamemsgmq', '-I/home/tylerzhong/QQMail/mmgamecenter/src/svrkit/mmgamedatadispatcher', '-I/home/tylerzhong/QQMail/mmgamecenter/src/comm/tlz/mm', '-I/home/tylerzhong/QQMail/mmgamecenter/src/comm/tlz/mm/bubble', '-I/home/tylerzhong/QQMail/mmgamecenter/src/cgi/mmocgamewap', '-I/home/tylerzhong/QQMail/mmgamecenter/src/cgi/mmocgameapp', '-I/home/tylerzhong/QQMail/mmgamecenter/src/cgi/mmgamefeedswap', '-I/home/tylerzhong/QQMail/mmgamecenter/src/comm', '-I/home/tylerzhong/QQMail/mmgamecenter/src', '-I/home/tylerzhong/QQMail/mmgamecenter', '-I/home/tylerzhong/QQMail', '-resource-dir=/data1/mm64/tylerzhong/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../clang_includes', '-fspell-checking'],
  'unsaved_files' : [('/data1/mm64/tylerzhong/QQMail/mmgamecenter/src/comm/dry/co/local_cache.h', '...', 3411)],
  'options' : 911,
}
2017-08-03 18:37:58,543 - ERROR - The ycmd server SHUT DOWN (restart with ':YcmRestartServer'). Unexpected exit code -11. Use the ':YcmToggleLogs' command to check the logs.
2017-08-03 18:38:05,488 - ERROR - Unable to connect to server
```

**Comment by zonyitoo** [comment] 2017-08-11 03:54
@vheon Can I have you attention? What could I do for help?

This bug bothers me a lot. I have no completion now...

**Comment by vheon** [comment] 2017-08-11 23:02
@zonyitoo you encounter a crash of libclang so something in your code makes it crash. there is no solution on our hand except finding a minimal reproducible case and send it to the libclang devs for them to fix libclang.

**Comment by zonyitoo** [comment] 2017-08-12 14:19
@vheon Ok, Thanks.

**Comment by zonyitoo** [comment] 2017-08-15 06:34
@vheon I have tried to recompile ycmd with clang3.9.1, 4.0.0, 4.0.1, but still crashed on the same error. It works fine with a old version of YouCompleteMe (ycmd) and clang 3.9.1.

So I don't think it is clang's fault.

I don't know exactly which commit I was on ... But I remember that version of YouCompleteMe `python/ycm/client/completion_request.py` has a global defined timeout in it.

**Comment by vheon** [comment] 2017-08-15 20:32
> I have tried to recompile ycmd with clang3.9.1, 4.0.0, 4.0.1 ..... It works fine with a old version of YouCompleteMe (ycmd) and clang 3.9.1

What do you mean by this? That you recompiled ycmd with different versions of clang? Well that would not change the version of libclang that we use since that is pinned to a specific version. If you have tried an older version of YouCompleteMe that used an older version of libclang and you do not reproduce the problem than probably is a regression in libclang but still not in YCM hands.

**Comment by zonyitoo** [comment] 2017-08-16 02:27
@vheon Hmm, I passed the `--system-libclang` to `install.py`. Because I was running on a customized Linux distribution. The `libclang` is built from source.

What I tried:

1. Older version of YouCompleteMe with
    - clang 3.9.1 -- Ok
    - clang 4.0.0 -- Ok
    - clang 4.0.1 -- Ok
2. Latest version of YouCompleteMe (master) with ycmd (`6463774`)
    - clang 3.9.1 -- Crashed
    - clang 4.0.0 -- Crashed
    - clang 4.0.1 -- Crashed
3. Latest version of YouCompleteMe (master) with ycmd (master)
    - clang 3.9.1 -- Crashed
    - clang 4.0.0 -- Crashed
    - clang 4.0.1 -- Crashed

So. I think we can believe that this is not clang's fault.

**Comment by puremourning** [comment] 2017-08-16 09:45
If building from source, disable asserts in clang when you build. Use Release rather than RelaseWithAsserts

**Comment by zonyitoo** [comment] 2017-08-16 09:47
Is it Ok to remove those asserts?

**Comment by puremourning** [comment] 2017-08-16 12:50
i think you want `-DCMAKE_BUILD_TYPE=Release`. You should ensure that the generated `LLVM_ENABLE_ASSERTIONS` is `OFF`.

Your testing is odd though. The only thing that changed in patch 655cc309 was something in our CI environment.

If you still have problems, try doing a git bisect to find which commit you think is changing it.

**Comment by puremourning** [comment] 2017-08-16 12:51
Also, if you can make a reproducible test case, then we can debug. But without that we're poking in the dark. Disabling assertions will certainly make the problem go away, but wn't fix the libclang or ycmd issue (whichever exists)

**Comment by zonyitoo** [comment] 2017-08-16 12:58
What I mean is that the **OLD** version that i was talking about is at commit 655cc309.

I can't make a minimal reproducible case. Because it only happens in our project, and it is very huge (with >100w lines of code). I don't even know which line of code make it crashed, and it just crashed somehow.

So I think some changes between 655cc309 -> master triggered this assertion.

BTW. I have tried `-DCMAKE_BUILD_TYPE=Release`, and it didn't disable that assertion. I have also tried to pass `-DCMAKE_CXX_FLAGS="-DNDEBUG"`, but the assertions are still there.

**Comment by puremourning** [comment] 2017-08-16 13:04
ok well set `-DLLVM_ENABLE_ASSERTIONS=OFF` then.

if you go the git bisect, then we can help. there have been a lot of commits since 8 Nov 2015

**Comment by zonyitoo** [comment] 2017-08-16 13:06
Ok. bisecting

**Comment by micbou** [comment] 2017-09-10 09:05
@asdyjd @zonyitoo Could you try again with the latest version of ycmd? A new version of Clang (5.0.0) is available.

**Comment by zonyitoo** [comment] 2017-09-10 14:37
1. I have failed to locate the problem by `bisect`, because not every commits between the master and the one I was using are working (lots of mysterious errors). It just failed to run, and I don't know why.

2. I just compiled clang5.0.0, and it works fine right now. I will continue test it in my projects and see if crashes can be reproduced.

**Comment by puremourning** [comment] 2017-09-10 14:39
FWIW, we're pretty sure that the issue was in libclang, and that libclang 5.0.0 will resolve it ;)

**Comment by micbou** [comment] 2017-09-24 11:55
Fixed by PR https://github.com/Valloric/ycmd/pull/832.

**Closed by micbou** 2017-09-24 11:55 UTC
