### ISSUE TITLE
Memory usage of ycmd

### ISSUE THREAD

**Issue by dgel** [Valloric/ycmd#474] opened 2016-05-02 00:09 UTC
I found out recently, that with a large-ish tags file, ycmd explodes in memory usage. A quick search showed me that this was deliberate, to make retrieval faster. I found a couple of places where memory usage could be improved while keeping the same algorithm (removing  30-40% of memory used, out of some 3GB for the tags found in the YouCompleteMe project), for which I'd be happy to open a PR.

However, in the course of looking this up, it occurred to me that scanning through a string is not a very expensive operation on modern cpu's, and the cache misses from the LetterNodes might mean that the 1kb/char memory overhead of LetterNodes isn't quite worth it. I've been doing some benchmarking of QueryMatchResult, comparing with a naive search through the string and came to 2 conclusions:

1. For identifiers of long length (50 chars), the approach using LetterNodes is about 3 times as fast, for reasonable length identifiers (20 chars), it's about 1.5 times as fast
2. The cost of creating a result when a match is found is an order of magnitude bigger than either of the two filtering methods.

For me, personally, the memory to speed trade-off that ycmd makes is not worth it in light of the costs it alreay makes. I can imagine it might be worth it to other people however, so I'd like to ask if you'd consider making the naive approach an option which could be set from, e.g., vimrc. for example using an identifier cutoff length after which the LetterNodes variant is used. The default could be 0 (current behaviour) and users could tweak the speed / memory tradeoff using it.

**Comment by Valloric** [comment] 2016-05-02 21:10
> if you'd consider making the naive approach an option which could be set from, e.g., vimrc. 

We're extremely unwilling to add more options to YCM. If we can improve the memory usage with a different algorithm that doesn't sacrifice perf & accuracy, we'll just do it for everyone.

I'm happy to look at any PRs that have specific improvements. Consider taking smaller steps with separate PRs that iteratively improve matters instead of one big one with all the changes you'd like to make.

> with a large-ish tags file, ycmd explodes in memory usage.

The root of the issue is the tags file approach; I consider adding support of tags files to YCM to be a mistake, and today that feature would not be added. We're not going to remove it because of backwards compatibility though, but improving it is not a high priority for us. PRs welcome of course. :)

**Comment by dgel** [comment] 2016-05-02 21:30
Could you elaborate a bit on why you think supporting tags files was a bad idea for YCM? Perhaps I should just change my ways instead of opening PRs ;)

I've already opened a PR with multiple changes, but they're not huge.. might open another PR for doing naive scans on shorter inputs, but I'm thinking that might be a tradeoff that you, unlike me, are unwilling to make as the common case will become somewhat slower

**Comment by Valloric** [comment] 2016-05-03 00:30
> ld you elaborate a bit on why you think supporting tags files was a bad idea for YCM? Perhaps I should just change my ways instead of opening PRs ;)

Tags are a massive hack. They're what some people use in the absence of semantic engines that can actually know exactly which identifiers are available at a particular point in the code. Tags are "let's just scan the codebase for all identifiers" approach which IMO sucks.

My opinion is that tags should not be used. Use a semantic engine for your language. If one doesn't exist, creating it is not a bad idea, although it is a lot of work.

Personally, when I'm editing code in a language that YCM does not have semantic support for, I just rely on YCM's built-in identifier completer. It will collect all the identifiers in the files I'm editing, which is more than good enough.

I never use tags.

> might open another PR for doing naive scans on shorter inputs, but I'm thinking that might be a tradeoff that you, unlike me, are unwilling to make as the common case will become somewhat slower

Your analysis is correct, I would indeed be unwilling to accept that tradeoff. :)

It's also not just perf. Changing the selection algo is a backwards-incompatible change for the mental model that users have of how YCM works. I'd be willing to make changes there _if_ it meant we'd have better ranking, but not worse.

And the perf is super important. I don't care too much about RAM usage; I'd make ycmd take _more_ RAM if that meant I could make it faster. My workstation at home has 16 GB RAM, and the one at work has 64 GB. IMO anyone editing code on a machine < 16 GB RAM is doing themselves a great disservice; RAM is cheap.

**Comment by dgel** [comment] 2016-05-03 21:18
Thanks for the explanation on tags. I agree they're a massive hack, but it's the only way I can get a 'do to definition' functionality that works on .cpp files I haven't opened yet, so sadly I need them. If ycm ever got the ability to do so without tags I'd not use them either.

> It's also not just perf. Changing the selection algo is a backwards-incompatible change for the mental model that users have of how YCM works. I'd be willing to make changes there if it meant we'd have better ranking, but not worse.

I think I wasn't very clear, I didn't mean to change the ranking algorithm, just to use a simpler version that just scans through a string for the needed information as opposed to building the LetterNode structure in order to skip through the string. On shorter strings the speed difference will be negligible (but still there), and we can keep using the LetterNode implementation on longer strings. Depending on where you set the length cutoff, the QueryMatchResult might be up to 50% slower for shorter strings, but I'm not sure if that's a big deal in this project or not.

Either way I'd like to get some benchmarking in this part of the project before I consider opening a PR for that. Even if you don't accept it, it would be very easy for me to keep a fork with only that change, for me personally. I'd prefer getting it in the main project though, of course

**Comment by dgel** [comment] 2016-05-06 10:21
Quick update: I've decided to stop using tags files in YCM, as I only really wanted them for code navigation in the first place. I've moved to using rtags, since it actually uses libclang and thus understands my code =). I'll keep working on making YCM use less memory though, I like it a lot and want to keep using it for code completion

**Comment by mrbiggfoot** [comment] 2016-06-20 09:48
I also have an issue with enormous ycmd memory usage.
There are two .cc and one .h files opened in vim. Three files total. The RES memory usage of python process that runs ycmd is 2GB at this point! I repeat, two gigabytes. Is it normal? Any hints how to fix this?
I already have "let g:ycm_collect_identifiers_from_tags_files = 0" in my vimrc.
Thanks!

Here's the 'top' output for completeness:
PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
5917 xxx        20   0 4464m 2.0g 173m S  0.0 26.0   1:05.71 python

**Comment by micbou** [comment] 2016-06-20 10:48
> There are two .cc and one .h files opened in vim.

What's the total number of lines of these files?

**Comment by mrbiggfoot** [comment] 2016-06-21 05:52
@micbou - 280 (.cc) + 4063 (.cc) + 136(.h) = 4479
Thanks for the response, I do hope you have a trick to fix the memory usage. In my normal workflow I usually have around 10-15 files opened, vim often eats up all the memory and I have to kill ycmd... with the whole machine being slowed down to crawl because of continuous swapping.

**Comment by mrbiggfoot** [comment] 2016-06-21 08:20
FYI - I tried rolling back to an older YCM and clang 3.6.2, and the issue still existed.

**Comment by dgel** [comment] 2016-06-21 08:34
Do these files perhaps include lots of headers (possibly transitively)? Perhaps using some large header-only libraries? If so, it's probably just due to YCM's memory usage, but otherwise there might be a bug somewhere

**Comment by mrbiggfoot** [comment] 2016-06-21 08:42
That's what I'm having right now: one .cc, three .h and one .proto (protobuf, which in theory should not add any memory usage), ... drumroll... 7.4Gb of resident memory usage!

I've been using YCM for the past year on the same code base, and this memory issue only started appearing about month or two ago. It is entirely possible that something in our code base has changed, so I'm looking for tips to debug / fix it.

@dgel - yes, the files include quite many headers, also from boost (many of which are header only).

**Comment by mrbiggfoot** [comment] 2016-06-21 08:49
Ok, that's an immediate question that I have:
Say, "foo.cc" includes "foo.h". When I open "foo.cc" in vim, the ycmd's RSS usage is around 750Mb. Now, I open "foo.h" in the same session, without closing "foo.cc". The RSS usage suddenly becomes 1.5Gb! But shouldn't "foo.h" have been parsed earlier, when YCM was processing "foo.cc"? If I understand correctly, the symbol table for "foo.h" should have been built already. That looks like a bug to me.

**Comment by Valloric** [comment] 2016-06-21 18:59
If you're pulling in lots of boost headers plus the pb.h headers that are generated from protocol buffers, your C++ translation unit is going to be huge. The memory usage comes from the cached ASTs in clang.

We can't really do anything about that. We have [a pending PR](https://github.com/Valloric/ycmd/pull/475) that reduces memory usage, but that should only help with the identifier completer and shouldn't do much in your case. You can try it out though.

**Comment by mrbiggfoot** [comment] 2016-06-21 19:32
@Valloric thanks for the response. What about the issue I described in my previous comment, about opening a header file that is already included in the opened source file? Is it not a bug?

**Comment by Valloric** [comment] 2016-06-21 23:02
> What about the issue I described in my previous comment, about opening a header file that is already included in the opened source file?

Those are separate translation units. You're confusing files and TUs. They're not the same.

**Comment by mrbiggfoot** [comment] 2016-06-26 18:48
@Valloric is there a way to show the amount of memory allocated by ycmd for each file? Here I mean file, not TU. Or maybe some approximation? I want to see what are the problematic includes that cause the memory bloat.

**Comment by puremourning** [comment] 2016-06-26 19:36
libclang does have some resource monitoring APIs, though none of them are exposed by ycmd, and they are almost certainly at the TU level.

Take a look at this: http://clang.llvm.org/doxygen/group__CINDEX__TRANSLATION__UNIT.html#gaacd1a1e9d83aaeec6b800e701b3a53f5 and related.

**Comment by vheon** [comment] 2016-07-03 19:04
Since #475 was merged I think this issue can be closed.

**Closed by vheon** 2016-07-03 19:04 UTC

**Comment by puremourning** [comment] 2016-07-16 18:43
@mrbiggfoot I have pushed [a branch `resource-usage`](https://github.com/puremourning/ycmd-1/tree/resource-usage-monitor) to my fork which reports the resource usage information from libclang (as linked above) when you run `:YcmDebugInfo`. Would you mind trying out on the files you're having problems with? Of course if the libclang memory usage report is sane, then it could be a ycmd issue (though i would be somewhat surprised).

**Comment by mrbiggfoot** [comment] 2016-07-17 16:14
@puremourning, thanks! Here's one example of the problematic memory usage (I modified some personal info such as file names):

```
Printing YouCompleteMe debug information...
-- Server has Clang support compiled in: True
-- Clang version: clang version 3.8.0 (tags/RELEASE_380/final)
-- C-family completer debug information:
--   Configuration file found and loaded
--   Configuration path: /home/xxx/projects/main/.ycm_extra_conf.py
--   Flags: ['-Wall', '-Wextra', '-Werror', '-Wno-enum-compare', '-Wno-ignored-qualifiers', '-Wno-unused-parameter', '-msse2', '-mcx16', '-mtune=sandybridge', '-D_GNU_SOURCE', '-D__
STDC_FORMAT_MACROS', '-DARENA_LSAN_LEVEL=1', '-Wno-invalid-offsetof', '-std=c++11', '-gcc-toolchain', '/opt/rh/devtoolset-3/root/usr', '-B', '-Qunused-arguments', '-Wno-deprecated-r
egister', '-Wno-unused-local-typedef', '-isystem', '/opt/rh/devtoolset-3/root/usr/include/c++/4.9.2', '-isystem', '/opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/x86_64-redhat-linu
x', '-isystem', '/opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/backward', '-I', '/home/xxx/projects/main', '-I', '/home/xxx/projects/main/build', '-I', '/home/xxx/p
rojects/main/build/toolchain/include', '-resource-dir=/home/xxx/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../clang_includes']
--   C-family completer resource usage:
-- TU /home/xxx/projects/main/foo.h using 381844922 bytes as:
--   - AST: 328093176
--   - Results Cache: 333467128
--   - Identifiers: 340020728
--   - Preprocessor: 351984185
--   - Selectors: 351988281
--   - Source Manager: 381844922
--
-- TU /home/xxx/projects/main/bar.cc using 298865697 bytes as:
--   - AST: 253982014
--   - Results Cache: 260568382
--   - Identifiers: 263681342
--   - Preprocessor: 273644871
--   - Selectors: 273648967
--   - Source Manager: 298865697
--
-- TU /home/xxx/projects/main/baz.cc using 241197102 bytes as:
--   - AST: 197204726
--   - Results Cache: 203332342
--   - Identifiers: 206232310
--   - Preprocessor: 216175623
--   - Selectors: 216179719
--   - Source Manager: 241197102
--
-- Server running at: http://127.0.0.1:56413
-- Server process ID: 6978
-- Server logfiles:
--   /tmp/ycm_temp/server_56413_stdout.log
--   /tmp/ycm_temp/server_56413_stderr.log
```

Just for completeness, here's the "top" output on these files:
```
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
 6978 xxx       20   0 4478m 2.1g 178m S  0.0 26.6   0:55.37 python
```

I'm not quite sure how to interpret these numbers, but if I naively add the numbers after the word "using", I get 880M. Does it mean that YCM overhead is ~140%?

Unfortunately I can't reproduce the bug with >7G usage by 2 files. IIRC I edited several files in one session, then closed all buffers except the two. When a buffer gets closed, does the correspondent TU memory get freed?

**Comment by mrbiggfoot** [comment] 2016-07-17 16:21
It just crossed my mind that most probably YcmDebugInfo reports virtual memory usage. If that's the case, my comment about 140% overhead is silly (I was comparing against physical memory usage).

**Comment by dgel** [comment] 2016-07-18 11:02
@mrbiggfoot I'm not sure about what might actually cause your issues, but as regards the >7G memory usage, it could be that part of this is caused by the memory reduction in newer versions of ycmd. 

I think the total memory usage is not so interesting here as the scaling behaviour.. `bar.cc` includes `foo.h` in your example? How does opening only `bar.cc` compare in memory usage to opening both `bar.cc` and `foo.h` in the same session? I'm not very familiar with this code but I'd expect AST memory usage (for example) to be shared between the open files, perhaps this is not happening?

**Comment by mrbiggfoot** [comment] 2016-07-18 12:19
@dgel:
1. both ```bar.cc``` and ```baz.cc``` include ```foo.h```.
2. Here's the output after opening only ```bar.cc```:
```
-- TU /home/xxx/projects/main/bar.cc using 298870245 bytes as:
--   - AST: 253982466
--   - Results Cache: 260568834
--   - Identifiers: 263681794
--   - Preprocessor: 273645323
--   - Selectors: 273649419
--   - Source Manager: 298870245
```
```
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
18709 xxx       20   0 3197m 769m 107m S  0.0  9.6   0:18.20 python
```

Here's the output after opening ```bar.cc``` and ```foo.h```:
```
-- TU /home/xxx/projects/main/foo.h using 381849018 bytes as:
--   - AST: 328093176
--   - Results Cache: 333467128
--   - Identifiers: 340020728
--   - Preprocessor: 351984185
--   - Selectors: 351988281
--   - Source Manager: 381849018
--
-- TU /home/xxx/projects/main/bar.cc using 298870245 bytes as:
--   - AST: 253982466
--   - Results Cache: 260568834
--   - Identifiers: 263681794
--   - Preprocessor: 273645323
--   - Selectors: 273649419
--   - Source Manager: 298870245
```
```
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
18709 xxx       20   0 4034m 1.6g 112m S  0.0 21.0   0:41.52 python
```

**Comment by dgel** [comment] 2016-07-21 15:56
It seems odd to me that including foo.h increases the memory usage by so much when it already has been parsed due to being included in bar.cc anyway. @puremourning is this expected?

**Comment by puremourning** [comment] 2016-07-21 18:32
It is. We parse each buffer as a separate TU

**Comment by f0s3** [comment] 2019-11-26 11:48
When I open a file with vim and then type something using YCM, and then exit and save with `:x`, multiple processes are spawned that pull my system from ~700mb used up to 3 (almost 4) gigs! I can make screenshots if you want me to (just in case this would help).
