### ISSUE TITLE
Header name u'X-Ycm-Hmac' is not a string 

### ISSUE THREAD

**Issue by windrg** [Valloric/ycmd#377] opened 2016-02-19 09:21 UTC
Hi, 
I feel that I'm getting close to the end of using `ycmd` with emacs. :-D
Somehow I've met this error once associating with `company-ycmd` 
(ref. [https://github.com/abingham/emacs-ycmd/issues/268](https://github.com/abingham/emacs-ycmd/issues/268))

```

AssertionError: Header name u'X-Ycm-Hmac' is not a string in (u'X-Ycm-Hmac', 'w47UWD3yjY/P7wFstf7FibWOeJrr/qpCaAMVauCHkMI=')
2016-02-19 18:12:13,584 - INFO - Received health request
<h1>Critical error while processing request: /healthy</h1>2016-02-19 18:12:13,585 - ERROR - Exception when serving /healthy
Traceback (most recent call last):
  File "/home/cysh/.emacs.d/bin/ycmd/third_party/waitress/waitress/channel.py", line 337, in service
    task.service()
  File "/home/cysh/.emacs.d/bin/ycmd/third_party/waitress/waitress/task.py", line 173, in service
    self.execute()
  File "/home/cysh/.emacs.d/bin/ycmd/third_party/waitress/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/cysh/.emacs.d/bin/ycmd/third_party/bottle/bottle.py", line 977, in __call__
    return self.wsgi(environ, start_response)
  File "/home/cysh/.emacs.d/bin/ycmd/third_party/bottle/bottle.py", line 972, in wsgi
    start_response('500 INTERNAL SERVER ERROR', headers, sys.exc_info())
  File "/home/cysh/.emacs.d/bin/ycmd/third_party/waitress/waitress/task.py", line 354, in start_response
    reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/home/cysh/.emacs.d/bin/ycmd/third_party/bottle/bottle.py", line 958, in wsgi
    start_response(response._status_line, response.headerlist)
  File "/home/cysh/.emacs.d/bin/ycmd/third_party/waitress/waitress/task.py", line 372, in start_response
    'Header name %r is not a string in %r' % (k, (k, v))
```
Could you let me know what's wrong in my env/settings, please?

Thanks.
ps : The last commit I built is
```
commit 7a105f593e7a216a93ad25ae046d9ba7ceae63f7
Merge: e93be12 7de567a
Author: Homu <homu@barosl.com>
Date:   Fri Feb 19 04:17:04 2016 +0900

    Auto merge of #374 - Valloric:coverage, r=puremourning
    
    [READY] More tests for functions in utils.py
    
    These tests cover lines that aren't being covered by other tests.
    
    Also includes minor refactoring & bug fixes.
    
    <!-- Reviewable:start -->
    [<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/374)
    <!-- Reviewable:end -->
```

**Comment by puremourning** [comment] 2016-02-19 09:41
Are you using Python 2? If so you need This PR: https://github.com/valloric/ycmd/pull/376

Just merge it in and you should be working. We just ported the code base to be both PY2 and PY3 compatible. There are some boggling issues. You're on the bleeding edge!

If you just want something stable, check out the commit before the PY3 merge.

**Comment by puremourning** [comment] 2016-02-19 09:42
Hahaha. s/boggling/niggling/

Sigh phone

**Comment by abingham** [comment] 2016-02-19 09:43
Hahaha! Github comments need a "like" button.

**Comment by windrg** [comment] 2016-02-19 10:25
Good to know, I've switched it to PY3. but then I've met an another error....still so far to the end??

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cysh/.emacs.d/bin/ycmd/ycmd/__main__.py", line 179, in <module>
    Main()
  File "/home/cysh/.emacs.d/bin/ycmd/ycmd/__main__.py", line 154, in Main
    extra_conf_store.CallGlobalExtraConfYcmCorePreloadIfExists()
  File "/home/cysh/.emacs.d/bin/ycmd/ycmd/../ycmd/extra_conf_store.py", line 73, in CallGlobalExtraConfYcmCorePreloadIfExists
    _CallGlobalExtraConfMethod( 'YcmCorePreload' )
  File "/home/cysh/.emacs.d/bin/ycmd/ycmd/../ycmd/extra_conf_store.py", line 91, in _CallGlobalExtraConfMethod
    module = Load( global_ycm_extra_conf, force = True )
  File "/home/cysh/.emacs.d/bin/ycmd/ycmd/../ycmd/extra_conf_store.py", line 149, in Load
    module = LoadPythonSource( _RandomName(), module_file )
  File "/home/cysh/.emacs.d/bin/ycmd/ycmd/../ycmd/utils.py", line 347, in LoadPythonSource
    return importlib.machinery.SourceFileLoader( name, pathname ).load_module()
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1614, in load_module
  File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/cysh/.emacs.d/bin/ycmd/cpp/ycm/.ycm_extra_conf.py", line 32, in <module>
    import ycm_core
ImportError: dynamic module does not define init function (PyInit_ycm_core)

Process ycmd-server exited abnormally with code 1
```

**Comment by micbou** [comment] 2016-02-19 10:29
Did you rebuild the `ycmd` libraries after switching?

**Comment by Valloric** [comment] 2016-02-19 18:33
This is fixed by #376.

**Comment by windrg** [comment] 2016-02-24 13:47
Ok, now it works well. BTW have you switched YCM also to PY3? I've tried to compile it. What's your suggestion for using both of YCM and YCMd?

**Comment by micbou** [comment] 2016-02-24 15:13
Not yet. You still need Python 2 to use YCM. Since the issue is resolved, I am closing it.

**Closed by micbou** 2016-02-24 15:13 UTC

**Comment by Yevgnen** [comment] 2016-02-25 10:10
I've have exactly the same error as @windrg as I try to use ycm in python3. I switch to python2 but the server says

    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/usr/local/ycmd/ycmd/__main__.py", line 181, in <module>
        Main()
      File "/usr/local/ycmd/ycmd/__main__.py", line 151, in Main
        options, hmac_secret = SetupOptions( args.options_file )
      File "/usr/local/ycmd/ycmd/__main__.py", line 128, in SetupOptions
        user_options = json.loads( ReadFile( options_file ) )
      File "/usr/local/ycmd/ycmd/../ycmd/utils.py", line 54, in ReadFile
        with open( filepath, encoding = 'utf8' ) as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    Process ycmd-server exited abnormally with code 1

**Comment by Valloric** [comment] 2016-02-25 19:34
@Yevgnen You probably forgot to run `git submodule update --init --recursive`

**Comment by Yevgnen** [comment] 2016-02-25 21:55
Nope, I did it. And I sorry for the unclear description. I build the server without any error by `./build.py --all` even thought I only the Python completion. The error happened in I try to start the server, not in the building progress.
