### ISSUE TITLE
Support for Language Server protocol announced by Microsoft, Red Hat and others

### ISSUE THREAD

**Issue by romix** [Valloric/ycmd#593] opened 2016-09-06 20:56 UTC
Microsoft, Red Hat and other have announces a Language Server protocol, which serves essentially the same role as the YCMD protocol:
https://github.com/Microsoft/language-server-protocol

This protocol is supported by Visual Studio Code, Eclipse and some other editors. It has good chances to become a de-facto standard for this kind of tasks.

Here is an example of integration with Eclipse Che:
https://github.com/eclipse/che/issues/1287

It would be nice if YCMD could support this protocol and thus it could be used with a much bigger set of editors and IDEs.

**Comment by micbou** [comment] 2016-09-07 09:49
Duplicate of #515.

**Closed by micbou** 2016-09-07 09:49 UTC
