### ISSUE TITLE
Code Completion for IOS project.

### ISSUE THREAD

**Issue by jojojames** [Valloric/ycmd#534] opened 2016-06-28 17:53 UTC
I'm trying to set up ycmd with completions for objective-c/iOS based from an xcode project. Semantic completions don't seem to be working.

I've set up a sample project here.
https://github.com/jojojames/DummyXcode

.ycm_extra_conf located here
https://github.com/jojojames/DummyXcode/blob/master/.ycm_extra_conf.py

compile_commands.json here
https://github.com/jojojames/DummyXcode/blob/master/compile_commands.json

I had a similar problem (using the same sample project as above) described here which was resolved through blacklisting some compile flags.
https://github.com/Andersbakken/rtags/issues/738

Not sure where to get a complete log (down to the clang error)
2016-06-28 10:45:16,497 - ERROR - Exception from semantic completer (using general): Traceback (most recent call last):
  File "/Users/james/.vim/dein/repos/github.com/Valloric/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/handlers.py", line 112, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/Users/james/.vim/dein/repos/github.com/Valloric/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 168, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/Users/james/.vim/dein/repos/github.com/Valloric/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 184, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/Users/james/.vim/dein/repos/github.com/Valloric/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 112, in ComputeCandidatesInner
    raise RuntimeError( NO_COMPLETIONS_MESSAGE )
RuntimeError: No completions found; errors in the file?

Using a more barebones ycm file that only specifies flags gets 70-80% of completions working.
https://github.com/jojojames/.emacs.d/blob/master/lang/objc/ycm_conf.py

**Comment by puremourning** [comment] 2016-06-28 23:46
Thanks for the detailed report. can you grab the output of :YcmDebugInfo? Also, what is the output of :YcmDiags?

Ultimately, the set of flags passed to libclang means that it can't parse your files correctly. Either your extra conf is passing the wrong flags, or there is some other issue. Usually it is the former, though it looks like you're using a compilation database, so it could be that we need to blacklist more flags like the rtags folk (who also use libclang to parse your code)  

The extra diags will help us work that out.

**Comment by jojojames** [comment] 2016-06-29 00:05
I'm using emacs-ycmd as a frontend for ycmd.

I tried opening the file in vim but got 'Native filetype completion not supported for current file, cannot force recompilation.' Might be something with my config for vim (haven't touched vim in a while).

Here's some debug info (just hunted around for some debug command `ycmd-show-debug-info'.
ycmd debug information for buffer AppDelegate.m in objc-mode:

Server has Clang support compiled in: True
Clang version: clang version 3.7.0 (tags/RELEASE_370/final)
Flags for /Users/james/Developer/DummyXcode/DummyXcode/AppDelegate.m loaded from /Users/james/Developer/DummyXcode/.ycm_extra_conf.py:
['/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang', '-x', 'c', '-x', 'objective-c', '-fmessage-length=0', '-fdiagnostics-show-note-include-stack', '-fmacro-backtrace-limit=0', '-std=gnu99', '-fobjc-arc', '-fmodules', '-fmodules-prune-interval=86400', '-fmodules-prune-after=345600', '-fbuild-session-file=/var/folders/k2/y7hdq90906d_5pgbt3_pt9jw0000gn/C/org.llvm.clang/ModuleCache/Session.modulevalidation', '-fmodules-validate-once-per-build-session', '-Wnon-modular-include-in-framework-module', '-Werror=non-modular-include-in-framework-module', '-Wno-trigraphs', '-fpascal-strings', '-Os', '-fno-common', '-Wno-missing-field-initializers', '-Wno-missing-prototypes', '-Werror=return-type', '-Wunreachable-code', '-Wno-implicit-atomic-properties', '-Werror=deprecated-objc-isa-usage', '-Werror=objc-root-class', '-Wno-arc-repeated-use-of-weak', '-Wduplicate-method-match', '-Wno-missing-braces', '-Wparentheses', '-Wswitch', '-Wunused-function', '-Wno-unused-label', '-Wno-unused-parameter', '-Wunused-variable', '-Wunused-value', '-Wempty-body', '-Wconditional-uninitialized', '-Wno-unknown-pragmas', '-Wno-shadow', '-Wno-four-char-constants', '-Wno-conversion', '-Wconstant-conversion', '-Wint-conversion', '-Wbool-conversion', '-Wenum-conversion', '-Wshorten-64-to-32', '-Wpointer-sign', '-Wno-newline-eof', '-Wno-selector', '-Wno-strict-selector-match', '-Wundeclared-selector', '-Wno-deprecated-implementations', '-DNS_BLOCK_ASSERTIONS=1', '-DOBJC_OLD_DISPATCH_PROTOTYPES=0', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk', '-fstrict-aliasing', '-Wprotocol', '-Wdeprecated-declarations', '-miphoneos-version-min=9.3', '-g', '-fvisibility=hidden', '-Wno-sign-conversion', '-fembed-bitcode-marker', '-iquote', '/Users/james/Developer/DummyXcode/build/DummyXcode.build/Release-iphoneos/DummyXcode.build/DummyXcode-generated-files.hmap', '-I/Users/james/Developer/DummyXcode/build/DummyXcode.build/Release-iphoneos/DummyXcode.build/DummyXcode-own-target-headers.hmap', '-I/Users/james/Developer/DummyXcode/build/DummyXcode.build/Release-iphoneos/DummyXcode.build/DummyXcode-all-target-headers.hmap', '-iquote', '/Users/james/Developer/DummyXcode/build/DummyXcode.build/Release-iphoneos/DummyXcode.build/DummyXcode-project-headers.hmap', '-I/Users/james/Developer/DummyXcode/build/Release-iphoneos/include', '-I/Users/james/Developer/DummyXcode/build/DummyXcode.build/Release-iphoneos/DummyXcode.build/DerivedSources/armv7', '-I/Users/james/Developer/DummyXcode/build/DummyXcode.build/Release-iphoneos/DummyXcode.build/DerivedSources', '-F/Users/james/Developer/DummyXcode/build/Release-iphoneos', 'dependencies', '--serialize-diagnostics', '-resource-dir=/Users/james/.vim/dein/repos/github.com/Valloric/YouCompleteMe/third_party/ycmd/ycmd/../clang_includes', '-isystem', '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1', '-isystem', '/usr/local/include', '-isystem', '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include', '-isystem', '/usr/include', '-isystem', '/System/Library/Frameworks', '-isystem', '/Library/Frameworks']

Server running at: 127.0.0.1:63842

Maybe @abingham can point me in the right direction for the matching Emacs commands.

**Comment by puremourning** [comment] 2016-07-03 18:47
I was able to determine that the flag which causes `libclang` to barf is `-MT dependencies`.

I discovered this by trial and error, by manually setting flags in `.ycm_extra_conf.py`.

The net result is that I now get the "Could not build module 'UIKit'" error which you also reported to tags. I don't know how you solved that, so I can't really progress (modules are a dark magic to me), but I think it is clear that the issue is the set of flags passed to libclang, not an issue with YCM itself.

@r4nt @d0k  any clue why `-MT dependencies` might cause `libclang` to be unable to parse a file?

```
  -MT <value>             Specify name of main file output in depfile
```

are as above. We can blacklist the depfiles-related flags I suppose, but I would like to understand a bit better before doing so.

**Comment by jojojames** [comment] 2016-07-03 19:01
Seems Rtags blacklists -MT also.

https://github.com/Andersbakken/rtags/commit/23c6c00fc70e6fa2b314e243cc75c9546a3c7e5f

**Comment by vheon** [comment] 2016-07-03 19:01
@puremourning I believed we already put `-MT` to the blacklist 😕

**Comment by vheon** [comment] 2016-07-03 19:02
https://github.com/Valloric/ycmd/blob/master/ycmd/completers/cpp/flags.py#L46

**Comment by puremourning** [comment] 2016-07-03 19:08
@vheon you're quite right.

And it is broken somehow.

```
:YcmDebugInfo
...
'-F/Users/ben/Development/YouCompleteMe/DummyXcode/build/Release-iphoneos', 'dependencies',
```

It removed `-MT` but not `dependencies`.

**Comment by vheon** [comment] 2016-07-03 19:09
@puremourning will you look into it? or should I?

**Comment by puremourning** [comment] 2016-07-03 19:09
I'll take a look now.

**Comment by puremourning** [comment] 2016-07-03 19:22
OK i see the problem. 

`-MD` and `-MMD` are don't take a file argument, but we have said they do, which leads to malformed flag lists.

I'll prep a PR.

**Comment by r4nt** [comment] 2016-07-04 07:33
Having a left-over 'dependencies' in there would make it barf. The question is why you need to blacklist -MT (I see no reason why, as with -fsyntax-only the dep file will not be written anyway)

**Comment by jojojames** [comment] 2016-07-22 18:55
Still seeing issues completing in the dummy project.

2016-07-22 11:54:20,413 - ERROR - Exception from semantic completer (using general): Traceback (most recent call last):
  File "/Users/james/.vim/dein/repos/github.com/Valloric/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/handlers.py", line 98, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/Users/james/.vim/dein/repos/github.com/Valloric/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 218, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/Users/james/.vim/dein/repos/github.com/Valloric/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 234, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/Users/james/.vim/dein/repos/github.com/Valloric/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 113, in ComputeCandidatesInner
    raise RuntimeError( NO_COMPLETIONS_MESSAGE )
RuntimeError: No completions found; errors in the file?

I'll try and see if I can get more details in the next few days.

**Comment by jojojames** [comment] 2016-08-10 00:22
Adding some more info here. Tried comparing a global ycm file vs local and it seems like the local completes less (at first glance) than using a global config.

Adding notes to this link https://github.com/jojojames/DummyXcode/blob/master/new.org as well as pasting it below.

* without ycm config (global config)
** Log
2016-08-09 17:13:25,594 - DEBUG - Global extra conf not loaded or no function YcmCorePreload
serving on http://127.0.0.1:52645
2016-08-09 17:13:25,640 - INFO - Received event notification
2016-08-09 17:13:25,640 - DEBUG - Event name: BufferVisit
2016-08-09 17:13:25,659 - INFO - Received event notification
2016-08-09 17:13:25,659 - DEBUG - Event name: FileReadyToParse
2016-08-09 17:13:25,659 - INFO - Adding buffer identifiers for file: /Users/james/Developer/DummyXcode/DummyXcode/AppDelegate.m
2016-08-09 17:13:31,363 - INFO - Received event notification
2016-08-09 17:13:31,363 - DEBUG - Event name: FileReadyToParse
2016-08-09 17:13:31,363 - INFO - Adding buffer identifiers for file: /Users/james/Developer/DummyXcode/DummyXcode/AppDelegate.m
2016-08-09 17:13:31,994 - INFO - Received completion request
2016-08-09 17:13:31,995 - DEBUG - Using filetype completion: True
2016-08-09 17:13:42,338 - INFO - Received debug info request
2016-08-09 17:13:55,637 - INFO - Received health request
** Debug
ycmd debug information for buffer AppDelegate.m in objc-mode:

Server has Clang support compiled in: True
Clang version: clang version 3.8.0 (tags/RELEASE_380/final)
C-family completer debug information:
  Configuration file found and loaded
  Configuration path: /Users/james/.emacs.d/lang/objc/ycm_conf.py
  Flags: ['-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk', '-I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/include', '-resource-dir=/Users/james/.emacs.d/ycmd/ycmd/../clang_includes', '-isystem', '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1', '-isystem', '/Library/Developer/CommandLineTools/usr/include/c++/v1', '-isystem', '/usr/local/include', '-isystem', '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include', '-isystem', '/Library/Developer/CommandLineTools/usr/include', '-isystem', '/usr/include', '-isystem', '/System/Library/Frameworks', '-isystem', '/Library/Frameworks', '-isystem', '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.3.0/include', '-fspell-checking']

Server running at: 127.0.0.1:52645
** Config
import os
import ycm_core

default_flags = [
'-isysroot',
'/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk',
'-I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/include'
]

def DirectoryOfThisScript():
  return os.path.dirname( os.path.abspath( __file__ ) )


def MakeRelativePathsInFlagsAbsolute( flags, working_directory ):
  if not working_directory:
    return list( flags )
  new_flags = []
  make_next_absolute = False
  path_flags = [ '-isystem', '-I', '-iquote', '--sysroot=' ]
  for flag in flags:
    new_flag = flag

    if make_next_absolute:
      make_next_absolute = False
      if not flag.startswith( '/' ):
        new_flag = os.path.join( working_directory, flag )

    for path_flag in path_flags:
      if flag == path_flag:
        make_next_absolute = True
        break

      if flag.startswith( path_flag ):
        path = flag[ len( path_flag ): ]
        new_flag = path_flag + os.path.join( working_directory, path )
        break

    if new_flag:
      new_flags.append( new_flag )
  return new_flags

# Thanks to https://github.com/decrispell/vim-config for this code
def FlagsForFile( filename, **kwargs ):
    """ given the source filename, return the compiler flags """
    opt_basename = '.clang_complete'
    curr_dir = os.path.dirname(filename)
    opt_fname = os.path.join(curr_dir, opt_basename)
    # keep traversing up the tree until we find the file, or hit the root
    while not os.path.exists(opt_fname):
        new_dir = os.path.dirname(curr_dir)
        if new_dir == curr_dir:
          # we've reached the root of the tree
          break
        curr_dir = new_dir
        opt_fname = os.path.join(curr_dir, opt_basename)
    try:
      fd = open(opt_fname, 'r')
    except IOError:
        return {'flags': default_flags, 'do_cache': True}
    flags = [line.strip() for line in fd.readlines()]
    relative_to = os.path.dirname(opt_fname)
    flags = MakeRelativePathsInFlagsAbsolute(flags, relative_to)
    return {
      'flags': flags, 'do_cache': True
    }
* with ycm config
** Log
2016-08-09 17:15:27,799 - DEBUG - Global extra conf not loaded or no function YcmCorePreload
serving on http://127.0.0.1:52670
2016-08-09 17:15:27,846 - INFO - Received event notification
2016-08-09 17:15:27,847 - DEBUG - Event name: BufferVisit
2016-08-09 17:15:27,866 - INFO - Received event notification
2016-08-09 17:15:27,866 - DEBUG - Event name: FileReadyToParse
2016-08-09 17:15:27,866 - INFO - Adding buffer identifiers for file: /Users/james/Developer/DummyXcode/DummyXcode/AppDelegate.m
Traceback (most recent call last):
  File "/Users/james/.emacs.d/ycmd/third_party/bottle/bottle.py", line 861, in _handle
    return route.call(**args)
  File "/Users/james/.emacs.d/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "/Users/james/.emacs.d/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 109, in wrapper
    return callback( *args, **kwargs )
  File "/Users/james/.emacs.d/ycmd/ycmd/../ycmd/hmac_plugin.py", line 72, in wrapper
    body = callback( *args, **kwargs )
  File "/Users/james/.emacs.d/ycmd/ycmd/../ycmd/handlers.py", line 67, in EventNotification
    event_handler )( request_data )
  File "/Users/james/.emacs.d/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 319, in OnFileReadyToParse
    flags = self._FlagsForRequest( request_data )
  File "/Users/james/.emacs.d/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 396, in _FlagsForRequest
    return self._flags.FlagsForFile( filename, client_data = client_data )
  File "/Users/james/.emacs.d/ycmd/ycmd/../ycmd/completers/cpp/flags.py", line 82, in FlagsForFile
    module = extra_conf_store.ModuleForSourceFile( filename )
  File "/Users/james/.emacs.d/ycmd/ycmd/../ycmd/extra_conf_store.py", line 54, in ModuleForSourceFile
    return Load( ModuleFileForSourceFile( filename ) )
  File "/Users/james/.emacs.d/ycmd/ycmd/../ycmd/extra_conf_store.py", line 65, in ModuleFileForSourceFile
    if Load( module_file ):
  File "/Users/james/.emacs.d/ycmd/ycmd/../ycmd/extra_conf_store.py", line 140, in Load
    if not _ShouldLoad( module_file ):
  File "/Users/james/.emacs.d/ycmd/ycmd/../ycmd/extra_conf_store.py", line 123, in _ShouldLoad
    raise UnknownExtraConf( module_file )
UnknownExtraConf: Found /Users/james/Developer/DummyXcode/.ycm_extra_conf.py. Load?

(Question can be turned off with options, see YCM docs)
2016-08-09 17:15:29,167 - INFO - Received extra conf load request
2016-08-09 17:15:29,202 - INFO - Received event notification
2016-08-09 17:15:29,202 - DEBUG - Event name: FileReadyToParse
2016-08-09 17:15:29,202 - INFO - Adding buffer identifiers for file: /Users/james/Developer/DummyXcode/DummyXcode/AppDelegate.m
2016-08-09 17:15:32,288 - INFO - Received event notification
2016-08-09 17:15:32,288 - DEBUG - Event name: FileReadyToParse
2016-08-09 17:15:32,288 - INFO - Adding buffer identifiers for file: /Users/james/Developer/DummyXcode/DummyXcode/AppDelegate.m
2016-08-09 17:15:32,796 - INFO - Received completion request
2016-08-09 17:15:32,796 - DEBUG - Using filetype completion: True
** Debug
ycmd debug information for buffer AppDelegate.m in objc-mode:

Server has Clang support compiled in: True
Clang version: clang version 3.8.0 (tags/RELEASE_380/final)
C-family completer debug information:
  Configuration file found and loaded
  Configuration path: /Users/james/Developer/DummyXcode/.ycm_extra_conf.py
  Flags: ['/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang', '-x', 'c', '-x', 'objective-c', '-fmessage-length=0', '-fdiagnostics-show-note-include-stack', '-fmacro-backtrace-limit=0', '-std=gnu99', '-fobjc-arc', '-fmodules', '-fmodules-prune-interval=86400', '-fmodules-prune-after=345600', '-fbuild-session-file=/var/folders/k2/y7hdq90906d_5pgbt3_pt9jw0000gn/C/org.llvm.clang/ModuleCache/Session.modulevalidation', '-fmodules-validate-once-per-build-session', '-Wnon-modular-include-in-framework-module', '-Werror=non-modular-include-in-framework-module', '-Wno-trigraphs', '-fpascal-strings', '-Os', '-fno-common', '-Wno-missing-field-initializers', '-Wno-missing-prototypes', '-Werror=return-type', '-Wunreachable-code', '-Wno-implicit-atomic-properties', '-Werror=deprecated-objc-isa-usage', '-Werror=objc-root-class', '-Wno-arc-repeated-use-of-weak', '-Wduplicate-method-match', '-Wno-missing-braces', '-Wparentheses', '-Wswitch', '-Wunused-function', '-Wno-unused-label', '-Wno-unused-parameter', '-Wunused-variable', '-Wunused-value', '-Wempty-body', '-Wconditional-uninitialized', '-Wno-unknown-pragmas', '-Wno-shadow', '-Wno-four-char-constants', '-Wno-conversion', '-Wconstant-conversion', '-Wint-conversion', '-Wbool-conversion', '-Wenum-conversion', '-Wshorten-64-to-32', '-Wpointer-sign', '-Wno-newline-eof', '-Wno-selector', '-Wno-strict-selector-match', '-Wundeclared-selector', '-Wno-deprecated-implementations', '-DNS_BLOCK_ASSERTIONS=1', '-DOBJC_OLD_DISPATCH_PROTOTYPES=0', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk', '-fstrict-aliasing', '-Wprotocol', '-Wdeprecated-declarations', '-miphoneos-version-min=9.3', '-g', '-fvisibility=hidden', '-Wno-sign-conversion', '-fembed-bitcode-marker', '-iquote', '/Users/james/Developer/DummyXcode/build/DummyXcode.build/Release-iphoneos/DummyXcode.build/DummyXcode-generated-files.hmap', '-I/Users/james/Developer/DummyXcode/build/DummyXcode.build/Release-iphoneos/DummyXcode.build/DummyXcode-own-target-headers.hmap', '-I/Users/james/Developer/DummyXcode/build/DummyXcode.build/Release-iphoneos/DummyXcode.build/DummyXcode-all-target-headers.hmap', '-iquote', '/Users/james/Developer/DummyXcode/build/DummyXcode.build/Release-iphoneos/DummyXcode.build/DummyXcode-project-headers.hmap', '-I/Users/james/Developer/DummyXcode/build/Release-iphoneos/include', '-I/Users/james/Developer/DummyXcode/build/DummyXcode.build/Release-iphoneos/DummyXcode.build/DerivedSources/armv7', '-I/Users/james/Developer/DummyXcode/build/DummyXcode.build/Release-iphoneos/DummyXcode.build/DerivedSources', '-F/Users/james/Developer/DummyXcode/build/Release-iphoneos', '-resource-dir=/Users/james/.emacs.d/ycmd/ycmd/../clang_includes', '-isystem', '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1', '-isystem', '/Library/Developer/CommandLineTools/usr/include/c++/v1', '-isystem', '/usr/local/include', '-isystem', '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include', '-isystem', '/Library/Developer/CommandLineTools/usr/include', '-isystem', '/usr/include', '-isystem', '/System/Library/Frameworks', '-isystem', '/Library/Frameworks', '-isystem', '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.3.0/include', '-fspell-checking']

Server running at: 127.0.0.1:52670
** Config
import os
import ycm_core

# These are the compilation flags that will be used in case there's no
# compilation database set (by default, one is not set).
# CHANGE THIS LIST OF FLAGS. YES, THIS IS THE DROID YOU HAVE BEEN LOOKING FOR.
flags = [
'-isysroot',
'/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk',
    '-I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/include',
]

# Set this to the absolute path to the folder (NOT the file!) containing the
# compile_commands.json file to use that instead of 'flags'. See here for
# more details: http://clang.llvm.org/docs/JSONCompilationDatabase.html
#
# You can get CMake to generate this file for you by adding:
#   set( CMAKE_EXPORT_COMPILE_COMMANDS 1 )
# to your CMakeLists.txt file.
#
# Most projects will NOT need to set this to anything; you can just change the
# 'flags' list of compilation flags. Notice that YCM itself uses that approach.
compilation_database_folder = '/Users/james/Developer/DummyXcode'

if os.path.exists( compilation_database_folder ):
  database = ycm_core.CompilationDatabase( compilation_database_folder )
else:
  database = None

SOURCE_EXTENSIONS = [ '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]

def DirectoryOfThisScript():
  return os.path.dirname( os.path.abspath( __file__ ) )

def MakeRelativePathsInFlagsAbsolute( flags, working_directory ):
  if not working_directory:
    return list( flags )
  new_flags = []
  make_next_absolute = False
  path_flags = [ '-isystem', '-I', '-iquote', '--sysroot=' ]
  for flag in flags:
    new_flag = flag

    if make_next_absolute:
      make_next_absolute = False
      if not flag.startswith( '/' ):
        new_flag = os.path.join( working_directory, flag )

    for path_flag in path_flags:
      if flag == path_flag:
        make_next_absolute = True
        break

      if flag.startswith( path_flag ):
        path = flag[ len( path_flag ): ]
        new_flag = path_flag + os.path.join( working_directory, path )
        break

    if new_flag:
      new_flags.append( new_flag )
  return new_flags


def IsHeaderFile( filename ):
  extension = os.path.splitext( filename )[ 1 ]
  return extension in [ '.h', '.hxx', '.hpp', '.hh' ]


def GetCompilationInfoForFile( filename ):
  # The compilation_commands.json file generated by CMake does not have entries
  # for header files. So we do our best by asking the db for flags for a
  # corresponding source file, if any. If one exists, the flags for that file
  # should be good enough.
  if IsHeaderFile( filename ):
    basename = os.path.splitext( filename )[ 0 ]
    for extension in SOURCE_EXTENSIONS:
      replacement_file = basename + extension
      if os.path.exists( replacement_file ):
        compilation_info = database.GetCompilationInfoForFile(
          replacement_file )
        if compilation_info.compiler_flags_:
          return compilation_info
    return None
  return database.GetCompilationInfoForFile( filename )


def FlagsForFile( filename, **kwargs ):
  if database:
    # Bear in mind that compilation_info.compiler_flags_ does NOT return a
    # python list, but a "list-like" StringVec object
    compilation_info = GetCompilationInfoForFile( filename )
    if not compilation_info:
      return None

    final_flags = MakeRelativePathsInFlagsAbsolute(
      compilation_info.compiler_flags_,
      compilation_info.compiler_working_dir_ )
  else:
    relative_to = DirectoryOfThisScript()
    final_flags = MakeRelativePathsInFlagsAbsolute( flags, relative_to )

  return {
    'flags': final_flags,
    'do_cache': True
  }

global ycm file
<img width="1057" alt="screenshot 2016-08-09 17 13 36" src="https://cloud.githubusercontent.com/assets/1227856/17537920/5828c5f0-5e55-11e6-806d-8a4104f649eb.png">

local ycm file
<img width="1057" alt="screenshot 2016-08-09 17 15 35" src="https://cloud.githubusercontent.com/assets/1227856/17537921/582b798a-5e55-11e6-83aa-a6f8fae4d820.png">

**Comment by jojojames** [comment] 2017-02-04 18:56
Bump 👍

**Comment by puremourning** [comment] 2017-02-20 18:55
@jojojames i can't read your previous post due to markdown. could you wrap the code in backpacks. see the GitHub flavoured markdown help for more info.

**Comment by puremourning** [comment] 2017-02-20 19:01
BTW: I can only successfully get YCM to work for even simple iOS projects when using Apple's libclang. This means using `--system-libclang` and sort of hoping that it otherwise works with ycmd. Basically, open source libclang can't compile for iOS platform, which is maybe sad but not super surprising.

**Comment by jojojames** [comment] 2017-02-20 19:48
@puremourning 

I will try at some point in the near future. I'm using irony-mode right now on Emacs as it's a little more performant for me for c/c++.

Irony-mode is also able to complete relatively decently for iOS projects (but also not perfect) and also can't complete Apple APIS. It's like you said, even basic completion doesn't seem to work on iOS with YCMD.

**Comment by jojojames** [comment] 2017-02-20 19:49
Also, when I used this, I was able to get Apple API completion. 

http://hyegar.com/2016/03/02/emacs-for-objc/

It's on my TODO list at some point to see if I can manually add those library apis to irony/ycmd.

**Comment by puremourning** [comment] 2017-02-20 19:51
PR #710 will really help too.

**Comment by jojojames** [comment] 2017-02-20 19:53
Also a link for anyone that wants to pull out a compile_commands.json from an xcode project.

https://github.com/supermarin/xcpretty

**Comment by puremourning** [comment] 2017-02-20 20:06
@jojojames does it work for you? I find that the compilation database it creates is not complete (it doesn't include file names for example)

**Comment by jojojames** [comment] 2017-02-20 20:09
That's whats being used to generate this file.

https://github.com/jojojames/DummyXcode/blob/master/compile_commands.json

I'm not versed enough to know if the above file is 100% in line of what you'd expect in a compile_commands.json though and not sure if there are any recent developments that would've affected that generation.

```
james ~ which xcpretty
/Users/james/.rvm/gems/ruby-2.3.0/bin/xcpretty
james ~ xcpretty -v
0.2.2
james ~
```

**Comment by puremourning** [comment] 2017-02-20 20:18
oh yeah, sorry i was being dumb. With my PR linked i can get pretty much fully working objective-c completion using that script and apple's libclang.

**Comment by puremourning** [comment] 2017-02-20 20:27
testing obj-c, c and c++ using files added to the project in Xcode including the standard library and all that jaz. Works fine with my PR, so I think that _actually_ closes this issue - sorry for prematurely closing it - i totally missed that our flag-mangling was the cause.

**Comment by jojojames** [comment] 2017-02-20 20:29
No problem at all! Thanks for all the hard work. 👍 

Once I have some time, I'll go ahead and give this a go and report back if something is amiss.

Thanks again!

I'm also wondering how you configure ycmd to use apple's libclang? I think I'm using the one supplied by either homebrew or macports at the moment.

**Comment by puremourning** [comment] 2017-02-20 20:50
@jojojames like this:

`./build.py <normal options> --system-libclang`

for example:

`./build.py --clang-completer --system-libclang`

we don't encourage use of `system-libclang` but if it is the only way, it is the only way :)

**Closed** 2017-05-20 22:48 UTC

**Comment by jojojames** [comment] 2017-05-21 16:42
@puremourning 

The fix works for me only if I include the ycm_extra_conf along with the compile_commands.json file.

If I remove the ycm_extra_conf, it'll complain about not finding compile flags. (Same github same project).

**Comment by puremourning** [comment] 2017-05-21 18:31
Can you check the location of your compile_commands.json and that the file paths all match (and in any case include the output of `:YcmDebugInfo`) ? 

In https://github.com/Valloric/ycmd/pull/680 we merged built-in support for compile_commands.json and the solution in this PR is invariant of the method used to collect the flags.

**Comment by jojojames** [comment] 2017-05-21 19:21
@puremourning 

I think you're right. I'll report back if it comes up again.
