### ISSUE TITLE
ycmd sometimes crash and report :ycm_core library compiled for Python 2 but loaded in Python 3

### ISSUE THREAD

**Issue by zijianyue** [Valloric/ycmd#599] opened 2016-09-12 09:33 UTC
I build ycmd in below method, and use it in emacs with emacs-ycmd. I'm on win7 64bit, I've uninstalled python3 ,but this issue still exist.Please help.

D:\ycmd-master>python build.py --all
Searching Python 2.7 libraries...
Found Python library: C:\Python27\libs\python27.lib
Found Python headers folder: C:\Python27\include
-- The C compiler identification is MSVC 19.0.23026.0
-- The CXX compiler identification is MSVC 19.0.23026.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Your C++ compiler does NOT support C++11, compiling in C++03 mode.
-- Found PythonLibs: C:/Python27/libs/python27.lib (found suitable version "2.7.10+", minimum required is "2.6")
Using Clang archive: D:/ycmd-master/cpp/../clang_archives/LLVM-3.9.0-win32.exe
Using libclang to provide semantic completion for C/C++/ObjC
Using external libclang: C:/Users/g00280886/AppData/Local/Temp/ycm_build.n5lt1s/lib/libclang.lib
-- Found PythonInterp: C:/Python27/python.exe (found version "2.7.10")
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/g00280886/AppData/Local/Temp/ycm_build.n5lt1s
Microsoft (R) 生成引擎版本 14.0.23107.0
版权所有(C) Microsoft Corporation。保留所有权利。

生成启动时间为 2016/9/12 17:24:07。

**Comment by micbou** [comment] 2016-09-12 10:07
What is the value of the `ycmd-server-command` option in your emacs configuration? Do you have more than one Python 2 installed on your machine?

**Comment by zijianyue** [comment] 2016-09-12 11:48
ycmd-server-command : ("c:/python27/python" "-u" "D:/ycmd-master/ycmd/")
Maybe the python in cygwin make ycmd confuse....   
But when I build ycmd ,it got the right path of my python 2.7.10.
Hope ycmd more stable.

**Comment by micbou** [comment] 2016-09-12 14:26
Go to the `ycmd` folder, start the Python interpreter and type the command:
```python
import ycm_core
```
If you get an error, paste its output.

**Comment by zijianyue** [comment] 2016-09-13 01:49
It seems no error.
D:\>cd ycmd-master

D:\ycmd-master>python
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ycm_core
>>>
>>>

**Comment by micbou** [comment] 2016-09-13 06:07
Could you paste the full output of the `*ycmd-server*` buffer when the error occurs?

**Comment by zijianyue** [comment] 2016-09-13 10:07
Because it did not happen after I renamed the python lib under cygwin(C:\cygwin\lib\python2.7--), so I close this issue.

**Comment by zijianyue** [comment] 2016-09-13 15:40
It occured when I use ycmd at home, below is the content of *ycmd-server*:
serving on http://127.0.0.1:13671
2016-09-13 23:14:05,825 - INFO - Received ready request
2016-09-13 23:14:05,835 - INFO - Received health request
2016-09-13 23:34:42,996 - INFO - Received event notification
2016-09-13 23:34:43,003 - INFO - Adding buffer identifiers for file: e:/projects/eNavi2_800X480_ChangeUI/Service/TG/MM/RM/Source/PMM/CRMPmm_Matching.cpp
2016-09-13 23:34:43,035 - INFO - Received event notification
2016-09-13 23:35:32,477 - INFO - Received completion request
2016-09-13 23:35:35,250 - INFO - Received completion request
2016-09-13 23:35:38,009 - INFO - Received completion request
2016-09-13 23:35:41,759 - INFO - Received completion request
2016-09-13 23:35:46,401 - INFO - Received completion request
2016-09-13 23:35:49,203 - INFO - Received completion request
2016-09-13 23:35:52,901 - INFO - Received completion request
2016-09-13 23:35:52,937 - ERROR - Exception from semantic completer (using general): Traceback (most recent call last):
  File "D:\ycmd\ycmd\..\ycmd\handlers.py", line 101, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "D:\ycmd\ycmd\..\ycmd\completers\completer.py", line 218, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "D:\ycmd\ycmd\..\ycmd\completers\completer.py", line 234, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "D:\ycmd\ycmd\..\ycmd\completers\cpp\clang_completer.py", line 113, in ComputeCandidatesInner
    raise RuntimeError( NO_COMPLETIONS_MESSAGE )
RuntimeError: No completions found; errors in the file?

2016-09-13 23:36:05,984 - INFO - Received command request
Traceback (most recent call last):
  File "D:\ycmd\third_party\bottle\bottle.py", line 861, in _handle
    return route.call(**args)
  File "D:\ycmd\third_party\bottle\bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "D:\ycmd\ycmd\..\ycmd\watchdog_plugin.py", line 109, in wrapper
    return callback( *args, **kwargs )
  File "D:\ycmd\ycmd\..\ycmd\hmac_plugin.py", line 72, in wrapper
    body = callback( *args, **kwargs )
  File "D:\ycmd\ycmd\..\ycmd\handlers.py", line 83, in RunCompleterCommand
    request_data ) )
  File "D:\ycmd\ycmd\..\ycmd\completers\completer.py", line 336, in OnUserCommand
    return command( self, request_data, arguments[ 1: ] )
  File "D:\ycmd\ycmd\..\ycmd\completers\cpp\clang_completer.py", line 125, in <lambda>
    self._GoTo( request_data ) ),
  File "D:\ycmd\ycmd\..\ycmd\completers\cpp\clang_completer.py", line 196, in _GoTo
    raise RuntimeError( 'Can\'t jump to definition or declaration.' )
RuntimeError: Can't jump to definition or declaration.
2016-09-13 23:36:09,400 - INFO - Received command request
Traceback (most recent call last):
  File "D:\ycmd\third_party\bottle\bottle.py", line 861, in _handle
    return route.call(**args)
  File "D:\ycmd\third_party\bottle\bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "D:\ycmd\ycmd\..\ycmd\watchdog_plugin.py", line 109, in wrapper
    return callback( *args, **kwargs )
  File "D:\ycmd\ycmd\..\ycmd\hmac_plugin.py", line 72, in wrapper
    body = callback( *args, **kwargs )
  File "D:\ycmd\ycmd\..\ycmd\handlers.py", line 83, in RunCompleterCommand
    request_data ) )
  File "D:\ycmd\ycmd\..\ycmd\completers\completer.py", line 336, in OnUserCommand
    return command( self, request_data, arguments[ 1: ] )
  File "D:\ycmd\ycmd\..\ycmd\completers\cpp\clang_completer.py", line 125, in <lambda>
    self._GoTo( request_data ) ),
  File "D:\ycmd\ycmd\..\ycmd\completers\cpp\clang_completer.py", line 196, in _GoTo
    raise RuntimeError( 'Can\'t jump to definition or declaration.' )
RuntimeError: Can't jump to definition or declaration.
2016-09-13 23:36:11,615 - INFO - Received command request
Traceback (most recent call last):
  File "D:\ycmd\third_party\bottle\bottle.py", line 861, in _handle
    return route.call(**args)
  File "D:\ycmd\third_party\bottle\bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "D:\ycmd\ycmd\..\ycmd\watchdog_plugin.py", line 109, in wrapper
    return callback( *args, **kwargs )
  File "D:\ycmd\ycmd\..\ycmd\hmac_plugin.py", line 72, in wrapper
    body = callback( *args, **kwargs )
  File "D:\ycmd\ycmd\..\ycmd\handlers.py", line 83, in RunCompleterCommand
    request_data ) )
  File "D:\ycmd\ycmd\..\ycmd\completers\completer.py", line 336, in OnUserCommand
    return command( self, request_data, arguments[ 1: ] )
  File "D:\ycmd\ycmd\..\ycmd\completers\cpp\clang_completer.py", line 125, in <lambda>
    self._GoTo( request_data ) ),
  File "D:\ycmd\ycmd\..\ycmd\completers\cpp\clang_completer.py", line 196, in _GoTo
    raise RuntimeError( 'Can\'t jump to definition or declaration.' )
RuntimeError: Can't jump to definition or declaration.
2016-09-13 23:36:15,141 - INFO - Received command request
Traceback (most recent call last):
  File "D:\ycmd\third_party\bottle\bottle.py", line 861, in _handle
    return route.call(**args)
  File "D:\ycmd\third_party\bottle\bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "D:\ycmd\ycmd\..\ycmd\watchdog_plugin.py", line 109, in wrapper
    return callback( *args, **kwargs )
  File "D:\ycmd\ycmd\..\ycmd\hmac_plugin.py", line 72, in wrapper
    body = callback( *args, **kwargs )
  File "D:\ycmd\ycmd\..\ycmd\handlers.py", line 83, in RunCompleterCommand
    request_data ) )
  File "D:\ycmd\ycmd\..\ycmd\completers\completer.py", line 336, in OnUserCommand
    return command( self, request_data, arguments[ 1: ] )
  File "D:\ycmd\ycmd\..\ycmd\completers\cpp\clang_completer.py", line 125, in <lambda>
    self._GoTo( request_data ) ),
  File "D:\ycmd\ycmd\..\ycmd\completers\cpp\clang_completer.py", line 196, in _GoTo
    raise RuntimeError( 'Can\'t jump to definition or declaration.' )
RuntimeError: Can't jump to definition or declaration.
2016-09-13 23:36:17,581 - INFO - Received command request
Traceback (most recent call last):
  File "D:\ycmd\third_party\bottle\bottle.py", line 861, in _handle
    return route.call(**args)
  File "D:\ycmd\third_party\bottle\bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "D:\ycmd\ycmd\..\ycmd\watchdog_plugin.py", line 109, in wrapper
    return callback( *args, **kwargs )
  File "D:\ycmd\ycmd\..\ycmd\hmac_plugin.py", line 72, in wrapper
    body = callback( *args, **kwargs )
  File "D:\ycmd\ycmd\..\ycmd\handlers.py", line 83, in RunCompleterCommand
    request_data ) )
  File "D:\ycmd\ycmd\..\ycmd\completers\completer.py", line 336, in OnUserCommand
    return command( self, request_data, arguments[ 1: ] )
  File "D:\ycmd\ycmd\..\ycmd\completers\cpp\clang_completer.py", line 125, in <lambda>
    self._GoTo( request_data ) ),
  File "D:\ycmd\ycmd\..\ycmd\completers\cpp\clang_completer.py", line 196, in _GoTo
    raise RuntimeError( 'Can\'t jump to definition or declaration.' )
RuntimeError: Can't jump to definition or declaration.
2016-09-13 23:36:21,341 - INFO - Received command request
Traceback (most recent call last):
  File "D:\ycmd\third_party\bottle\bottle.py", line 861, in _handle
    return route.call(**args)
  File "D:\ycmd\third_party\bottle\bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "D:\ycmd\ycmd\..\ycmd\watchdog_plugin.py", line 109, in wrapper
    return callback( *args, **kwargs )
  File "D:\ycmd\ycmd\..\ycmd\hmac_plugin.py", line 72, in wrapper
    body = callback( *args, **kwargs )
  File "D:\ycmd\ycmd\..\ycmd\handlers.py", line 83, in RunCompleterCommand
    request_data ) )
  File "D:\ycmd\ycmd\..\ycmd\completers\completer.py", line 336, in OnUserCommand
    return command( self, request_data, arguments[ 1: ] )
  File "D:\ycmd\ycmd\..\ycmd\completers\cpp\clang_completer.py", line 125, in <lambda>
    self._GoTo( request_data ) ),
  File "D:\ycmd\ycmd\..\ycmd\completers\cpp\clang_completer.py", line 196, in _GoTo
    raise RuntimeError( 'Can\'t jump to definition or declaration.' )
RuntimeError: Can't jump to definition or declaration.
2016-09-13 23:36:26,193 - INFO - Received command request
2016-09-13 23:36:28,990 - INFO - Received command request

**Comment by micbou** [comment] 2016-09-13 19:46
I now understand the issue. You are experiencing a libclang crash, which is not a big surprise on Windows. Try to build a testcase as minimal as you can with the least amount of flags, that consistently reproduces the crash and share it here. Ideally, it should consist of one source file with its `.ycm_extra_conf.py`.

You may wonder why the error message you get is totally unrelated to the issue. This is because emacs-ycmd interprets signals from the ycmd process as exit codes. In your case, ycmd is killed by signal 6 (`SIGABRT`) while an exit code of 6 means that the ycm_core library is compiled for Python 2 but loaded in Python 3. I've reported [the issue on the emacs-ycmd repository](https://github.com/abingham/emacs-ycmd/issues/352).

**Comment by zijianyue** [comment] 2016-09-14 07:54
OK, I'll try to reproduce it with a minimal case.

**Comment by micbou** [comment] 2016-12-05 23:33
I am closing the issue as we can't do much without a reproducible case. We'll be happy to reopen if one is provided.

**Closed by micbou** 2016-12-05 23:33 UTC

**Comment by zijianyue** [comment] 2016-12-06 04:43
I found that when I use ycmd-goto-imprecise or ycmd-getparent-imprecise, ycmd never crash, it seems that crash will happen when reparse the buffer.
