### ISSUE TITLE
Migrate Rust completer to Rust Language Server

### ISSUE THREAD

**Issue by miguelsaldivar** [Valloric/ycmd#1105] opened 2018-09-18 21:58 UTC
So it seems that [racerd](https://github.com/jwilm/racerd), has stalled and hasn't been updated in a year. Were there plans to move to a different rust completion server?

**Comment by puremourning** [comment] 2018-09-18 21:59
Such as?

**Comment by bstaletic** [comment] 2018-09-18 22:00
Last I heard RLS was in a fairly good shape. As in Rust Language Server.

**Comment by miguelsaldivar** [comment] 2018-09-18 22:07
Yeah I think [RLS](https://github.com/rust-lang-nursery/rls) would be nice, it seems like it's heavily used and updated regularly.

**Comment by puremourning** [comment] 2018-09-18 22:10
Do you have specific issues that it would address?

**Comment by bstaletic** [comment] 2018-09-18 22:16
@puremourning We already have a couple unresolved rust related issues that might go away with RLS. It might be worth a try.

**Comment by puremourning** [comment] 2018-09-18 22:40
Fair enough. As always provided there is a benefit and no regression and a completely free migration path... :)

Then again I don’t Rust so PRs welcome?

**Comment by micbou** [comment] 2018-09-18 22:44
There is a rough implementation in [that branch](https://github.com/micbou/ycmd/tree/rust-language-server). If people are interested, I may polish it and submit a PR.

**Comment by miguelsaldivar** [comment] 2018-09-18 23:00
Oh awesome @micbou :sunglasses:, if you need any help let me know and I'll try to find some time to help. 
@puremourning a bunch of small things like: auto completion on types from [extern blocks](https://github.com/racer-rust/racer/issues/890).

**Comment by Valloric** [comment] 2018-10-06 18:37
We'll eventually need to migrate to RLS since racer is deadish. Also, RLS is powered by racer internally (for the initial RLS implementation).

@jwilm Thoughts?

**Comment by bstaletic** [comment] 2018-10-06 19:20
@micbou Says there's not too much work left to polish his branch enough for migration.

**Comment by jwilm** [comment] 2018-10-07 14:55
RLS capabilities are a super set of Racer's; there's no technical reasons ycmd shouldn't use RLS at this point. There may be some other benefits like eliminating a Rust build step in ycmd in favor of "make sure rls is installed on your system". I believe this comes as a component with rustup today.

**Comment by puremourning** [comment] 2019-01-29 09:37
We are currently working on [significantly reducing the overhead in adding new LSP based completers](https://github.com/puremourning/ycmd-1/commit/eb915e410d9576d4ae9aef674baf7f8245e14c81).

When this is complete we will review which servers offer value and stability. We'll keep this in mind.

**Comment by Valloric** [comment] 2019-02-12 04:20
While RLS has its problems, it's the obvious next step for our Rust integration. 

@puremourning I love that we're making integrating LSP completers easier! Great work and thank you! :) This will pay off a lot going forward since lots of semantic engines are moving towards implementing the LSP spec.

**Comment by bstaletic** [comment] 2019-06-14 09:58
The RLS PR has been merged.

**Closed by bstaletic** 2019-06-14 09:58 UTC
